import {reserveTeacherCode} from '@/lib/teacher-access-code';
import {userVoices} from '@/lib/voice-server';
import {paymentState} from '@/lib/billing';
import {tracksFromRow,courseFor,bookFamily,reviewUnit} from '@/lib/study-tracks';
import {selectedTracks,selectedTrack,trackFields,updateSelection} from '@/lib/study-tracks-server';
import {savedWordExercises} from '@/lib/word-examples-server';
import {isEssential,bookWords} from '@/lib/essential';
import {schoolScope,centerContext} from '@/lib/center-context';
import {notify,notifyGroups,ensureDailyInbox} from '@/lib/notifications-server';
import {tashkentDate} from '@/lib/billing';
import {AppError,administrator,resignTemporaryAdministrator,current,db,fail,mutation,permitted,safeUser,staff,teacher,textValue,verifyPassword,hashPassword,digest} from '@/lib/school-server';
import {books,bookById} from '@/lib/catalog';
import {lessonExercises,evaluate,requiredLessons} from '@/lib/lessons';
import type {Attempt} from '@/lib/school-types';
export const runtime='nodejs';
function attempt(r:any):Attempt{return{id:r.id,userId:r.user_id,book:r.book,unit:r.unit,lesson:r.lesson,answers:r.answers,score:r.score,total:r.total,seconds:r.seconds,completed:r.completed,createdAt:r.created_at,grade:r.grade,comment:r.comment}}
export async function GET(req:Request){return schoolScope(async()=>{try{const u=await current(req,true);const isStaff=!['student','advertiser'].includes(u.role);const focus=new URL(req.url).searchParams.get('student');if(focus&&!isStaff)throw new AppError('Access denied.',403);const [users,groups,assignments,events,attempts,reads,progress,stats]=await Promise.all([isStaff?db('school_users','GET',undefined,'order=created_at.desc'):Promise.resolve([]),db('school_groups'),db('school_assignments','GET',undefined,'order=created_at.desc'),db('school_events','GET',undefined,'order=at.asc'),db('school_attempts','GET',undefined,`user_id=eq.${encodeURIComponent(isStaff&&focus?focus:u.id)}&order=created_at.desc&limit=1000`),db('school_reads','GET',undefined,`user_id=eq.${u.id}`),db('school_progress','GET',undefined,`user_id=eq.${u.id}`),isStaff?db('rpc/school_student_stats','POST',{}):Promise.resolve([])]);for(const s of users){if(!s.billing){s.billing={status:'paid',paidAt:tashkentDate()};await db('school_users','PATCH',{billing:s.billing},`id=eq.${s.id}`)}}await ensureDailyInbox(u,groups,assignments,events);const inbox=await db('school_inbox','GET',undefined,`user_id=eq.${u.id}&order=created_at.desc&limit=100`);return Response.json({actor:centerContext.getStore()?.actor,demo:!!centerContext.getStore()?.demo||u.role==='advertiser'&&centerContext.getStore()?.actor?.role==='owner',voiceOptions:userVoices(u),centerPayment:(await db('school_centers','GET',undefined,`id=eq.${encodeURIComponent(u.centerId)}`))[0]?.billing?paymentState((await db('school_centers','GET',undefined,`id=eq.${encodeURIComponent(u.centerId)}`))[0].billing):undefined,notifications:inbox.map((n:any)=>({id:n.id,title:n.title,body:n.body,kind:n.kind,read:n.read,createdAt:n.created_at})),user:u,users:users.map(safeUser),groups:groups.filter((g:any)=>isStaff||g.id===u.groupId).map((g:any)=>({teacherId:g.teacher_id,id:g.id,name:g.name,days:g.days,time:g.time,reminderTime:g.reminder_time})),assignments:assignments.filter((a:any)=>isStaff||u.groupId&&a.groups.includes(u.groupId)).map((a:any)=>({id:a.id,title:a.title,text:a.body,groups:a.groups,extra:a.extra,createdAt:a.created_at})),events:events.filter((e:any)=>isStaff||e.allGroups||u.groupId&&e.groups.includes(u.groupId)),attempts:u.role==='student'&&u.payment.blocked?[]:attempts.map(attempt),progress:u.role==='student'&&u.payment.blocked?[]:progress,stats,read:reads.map((r:any)=>r.assignment_id),vapidKey:process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY||''},{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}})}
export async function POST(req:Request){return schoolScope(async()=>{try{mutation(req);const d=await req.json();const u=await current(req,['notificationRead','notificationsRead','profile','settings','push','unpush'].includes(d.action));if(u.role==='owner'&&!centerContext.getStore()?.centerId&&!['settings','profile','notificationRead','notificationsRead','push','unpush','submit','read'].includes(d.action))throw new AppError('Open a learning centre before changing its data.',403);if(u.role==='advertiser'&&!['settings','profile','notificationRead','notificationsRead','push','unpush'].includes(d.action))throw new AppError('Choose a demonstration role in Settings.',403);switch(d.action){
case 'notificationsRead':{if(!Array.isArray(d.ids)||d.ids.length>100||!d.ids.every((id:any)=>typeof id==='string'&&id.length<200))throw new AppError('Invalid notification list.');const rows=await db('school_inbox','GET',undefined,`user_id=eq.${encodeURIComponent(u.id)}`);const requested=new Set(d.ids);const owned=rows.filter((n:any)=>requested.has(n.id));if(owned.length!==requested.size)throw new AppError('Access denied.',403);for(const n of owned.filter((n:any)=>!n.read))await db('school_inbox','PATCH',{read:true},`id=eq.${encodeURIComponent(n.id)}&user_id=eq.${encodeURIComponent(u.id)}`);break}
case 'notificationRead':{const rows=await db('school_inbox','GET',undefined,`id=eq.${encodeURIComponent(d.id)}`);if(!rows[0]||rows[0].user_id!==u.id)throw new AppError('Access denied.',403);await db('school_inbox','PATCH',{read:true},`id=eq.${encodeURIComponent(d.id)}`);break}
case 'payment':{administrator(u);const rows=await db('school_users','GET',undefined,`id=eq.${encodeURIComponent(d.id)}`);const s=rows[0];if(!s||s.role!=='student'||!['paid','unpaid'].includes(d.status))throw new AppError('Choose a student and payment status.');const today=tashkentDate();const billing=d.status==='paid'?{status:'paid',paidAt:today}:{status:'unpaid',paidAt:s.billing?.paidAt||null,unpaidAt:safeUser(s).payment.unpaidAt||today};await db('school_users','PATCH',{billing},`id=eq.${s.id}`);await db('school_payments','POST',{user_id:s.id,status:d.status,at:new Date().toISOString(),by:u.id});await notify(s.id,d.status==='paid'?'To‘lov tasdiqlandi':'Oylik to‘lovni tezroq to‘lang',d.status==='paid'?'Darslardan foydalanishingiz mumkin.':'7 kun ichida to‘lov tasdiqlanmasa darslarga kirish yopiladi.','payment',s.id);break}
case 'teacherManage':{administrator(u);const rows=await db('school_users','GET',undefined,`id=eq.${encodeURIComponent(d.id)}`);if(!(rows[0]?.role==='teacher'||u.role==='owner'&&rows[0]?.role==='administrator')||typeof d.disabled!=='boolean')throw new AppError('Choose a teacher.');await db('school_users','PATCH',{disabled:d.disabled},`id=eq.${encodeURIComponent(d.id)}`);if(d.disabled)await db('school_sessions','DELETE',undefined,`user_id=eq.${encodeURIComponent(d.id)}`);break}
case 'teacherPassword':{administrator(u);const rows=await db('school_users','GET',undefined,`id=eq.${encodeURIComponent(d.id)}`);if(!(rows[0]?.role==='teacher'||u.role==='owner'&&rows[0]?.role==='administrator'))throw new AppError('Choose a teacher.');const {hashPassword}=await import('@/lib/school-server');const password=textValue(d.password,128);if(password.length<8)throw new AppError('Use at least 8 characters.');await db('school_users','PATCH',{password_hash:hashPassword(password)},`id=eq.${encodeURIComponent(d.id)}`);await db('school_sessions','DELETE',undefined,`user_id=eq.${encodeURIComponent(d.id)}`);break}
case 'profile':{const rows=await db('school_users','GET',undefined,`id=eq.${encodeURIComponent(u.id)}`),r=rows[0];if(!r)throw new AppError('Account not found.',404);if(u.role==='owner'){const code=textValue(d.currentCode,256);const valid=r.teacher_code_hash?digest('teacher-personal:'+code)===r.teacher_code_hash:!!process.env.OWNER_ACCESS_CODE&&digest(code)===digest(process.env.OWNER_ACCESS_CODE.trim());if(!valid)throw new AppError('Your current Owner code is incorrect. / Hozirgi Owner kodi noto‘g‘ri.',403);if(d.newPassword)throw new AppError('Owner signs in with a code.',400)}if(u.role!=='owner'&&centerContext.getStore()?.actor?.role!=='owner'&&!verifyPassword(textValue(d.currentPassword,128),r.password_hash))throw new AppError('Your current password is incorrect. / Hozirgi parolingiz noto‘g‘ri.',403);const first=textValue(d.firstName,60),last=u.role==='owner'&&!d.lastName?'':textValue(d.lastName,60),name=(first+' '+last).normalize('NFKC').toLowerCase().replace(/\s+/g,' ').replace(/[‘’ʻʼ]/g,"'");const duplicates=await db('school_users','GET',undefined,`login_name=eq.${encodeURIComponent(name)}`);if(duplicates.some((s:any)=>s.id!==u.id&&s.role===r.role&&(s.center_id||'zamon')===(r.center_id||'zamon')))throw new AppError('This name is already in use in your centre. / Bu ism-familiya markazingizda mavjud.',409);const patch:any={first_name:first,last_name:last,login_name:name};if(d.newPassword){const password=textValue(d.newPassword,128);if(password.length<8)throw new AppError('Use at least 8 characters for the password.');patch.password_hash=hashPassword(password)}if(d.personalCode){if(!['teacher','admin','administrator','owner','advertiser'].includes(u.role))throw new AppError('Personal sign-in codes are for staff.',403);patch.teacher_code_hash=await reserveTeacherCode(u.id,d.personalCode)}await db('school_users','PATCH',patch,`id=eq.${encodeURIComponent(u.id)}`);if(d.newPassword||d.personalCode){const currentToken=req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith('school_session='))?.slice(15);const sessions=await db('school_sessions','GET',undefined,`user_id=eq.${encodeURIComponent(u.id)}`);for(const session of sessions)if(!currentToken||session.token!==digest(currentToken))await db('school_sessions','DELETE',undefined,`id=eq.${encodeURIComponent(session.id)}`)}return Response.json({ok:true})}
case 'settings':{const s=d.settings||{};const styles=['classic','ocean','forest','sunset','rose','midnight','notebook','terminal','editorial','orbit'];if(s.voice&&!userVoices(u).some(v=>v.id===s.voice))throw new AppError('Voice unavailable.',403);if(!styles.includes(s.style)||!['en','uz'].includes(s.language)||!['cards','list','compact'].includes(s.layout)||s.accent&&!/^#[0-9a-f]{6}$/i.test(s.accent)||!(s.audioRate>=.5&&s.audioRate<=1.2))throw new AppError('Invalid preferences.');await db('school_users','PATCH',{settings:s},`id=eq.${u.id}`);break}
case 'submit':{const book=textValue(d.book,30),unit=Number(d.unit),lesson=textValue(d.lesson,100);if(!permitted(u,book,unit))throw new AppError('This Unit is locked.',403);if(lesson==='test')throw new AppError('Open the Unit test.');const qs:import('@/lib/school-types').Exercise[]=/^essential-[2-6]$/.test(book)?await savedWordExercises(u,book,unit,lesson,d.exerciseSession):lessonExercises(book,unit,lesson);if(!qs.length||!Array.isArray(d.answers)||d.answers.length!==qs.length)throw new AppError('Complete all questions first.');const previous=await db('school_progress','GET',undefined,`user_id=eq.${u.id}&book=eq.${book}&unit=eq.${unit}`);const done=new Set<string>(previous.map((a:any)=>a.lesson));const course=courseFor(u,book);if(unit===course?.startUnit)requiredLessons(book,unit).slice(0,course.startLesson-1).forEach(l=>done.add(l));if(u.role==='student'&&!reviewUnit(u,book,unit)){const required=requiredLessons(book,unit);if(lesson==='test'&&!required.every(l=>done.has(l)))throw new AppError('Finish the lessons before the Unit test.');if(!isEssential(book)&&lesson!=='test'){const i=required.indexOf(lesson);if(i<0||!required.slice(0,i).every(l=>done.has(l)))throw new AppError('Finish the previous lesson first.',403)}if(isEssential(book)&&lesson!=='test'){const i=required.indexOf(lesson);if(i<0||i>=3+required.filter(l=>done.has(l)).length)throw new AppError('Finish an open word first.',403)}}const answers=qs.map((q,i)=>{const a=typeof d.answers[i]==='string'?d.answers[i].slice(0,4000):'';return{question:q.prompt,answer:a,correct:q.open?'Teacher review':q.answer,ok:evaluate(q,a),...(!q.open&&!isEssential(book)?{task:{id:book+'-'+unit+'-'+lesson+'-'+q.id,kind:q.kind==='speaking'?'speaking':q.kind==='choice'?'choice':q.id.includes('-order-')?'order':'dictation',prompt:q.prompt,answer:q.answer,audio:q.audio||q.answer,...(q.options?{options:q.options}:{})}}:{}),struggled:Array.isArray(d.firstAnswers)&&typeof d.firstAnswers[i]==='string'&&!evaluate(q,d.firstAnswers[i])}});const score=answers.filter(a=>a.ok).length;await db('school_attempts','POST',{user_id:u.id,book,unit,lesson,answers,score,total:qs.length,seconds:Math.min(7200,Math.max(0,Math.round(Number(d.seconds)||0))),completed:score===qs.length});if(score===qs.length)await db('school_progress','POST',{user_id:u.id,book,unit,lesson},'on_conflict=user_id,book,unit,lesson');break}
case 'read':{const rows=await db('school_assignments','GET',undefined,`id=eq.${encodeURIComponent(d.id)}`);if(!rows[0]||u.role==='student'&&!rows[0].groups.includes(u.groupId))throw new AppError('Assignment not available.',403);await db('school_reads','POST',{user_id:u.id,assignment_id:d.id},'on_conflict=user_id,assignment_id');break}
case 'group':{staff(u);if(u.role==='admin'&&!d.id)throw new AppError('Only your teacher can create groups.',403);const name=textValue(d.name,100);if(!Array.isArray(d.days)||!d.days.length||!d.days.every((v:any)=>Number.isInteger(v)&&v>=0&&v<=6)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(d.time)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(d.reminderTime))throw new AppError('Choose lesson days and times.');await db('school_groups',d.id?'PATCH':'POST',{subject_id:centerContext.getStore()?.subjectId||'english',name,days:d.days,time:d.time,reminder_time:d.reminderTime,...(!d.id&&u.role==='teacher'?{teacher_id:u.id}:{})},d.id?`id=eq.${encodeURIComponent(d.id)}`:'');break}
case 'student':{staff(u);const rows=await db('school_users','GET',undefined,`id=eq.${encodeURIComponent(d.id)}`);const target=rows[0];if(!target||!['student','admin'].includes(target.role))throw new AppError('Choose a student or admin.');if(d.groupId){const gs=await db('school_groups','GET',undefined,`id=eq.${encodeURIComponent(d.groupId)}`);if(!gs[0])throw new AppError('Group not found.');}if(centerContext.getStore()?.subjectId!=='english'&&(d.tracks||d.book))throw new AppError('English ruxsatlarini faqat English fanida o‘zgartiring.',403);let courses=tracksFromRow(target);if(d.tracks){const next=selectedTracks(d.tracks);courses={navigate:updateSelection(courses.navigate,next.navigate),essential:updateSelection(courses.essential,next.essential)};}else if(d.book){const family=bookFamily(d.book),next=selectedTrack({book:d.book,unit:d.unit,startLesson:d.startLesson},family);courses[family]=updateSelection(courses[family],next);}await db('school_users','PATCH',{...(Array.isArray(target.enrollments)?{enrollments:target.enrollments.map((e:any)=>e.subjectId===(centerContext.getStore()?.subjectId||'english')&&e.centerId===centerContext.getStore()?.centerId?{...e,groupId:d.groupId||null}:e)}:{}),...(!target.enrollments||target.enrollments[0]?.subjectId===centerContext.getStore()?.subjectId?{group_id:d.groupId||null}:{}),...trackFields(courses)},`id=eq.${encodeURIComponent(d.id)}`);break}
case 'setStudyTrack':{staff(u);if(!['navigate','essential'].includes(d.family))throw new AppError('Choose a course.');const rows=await db('school_users','GET',undefined,`id=eq.${encodeURIComponent(d.id)}`);const target=rows[0];if(!target||!['student','admin'].includes(target.role))throw new AppError('Choose a student or admin.');const tracks=tracksFromRow(target);tracks[d.family as 'navigate'|'essential']=updateSelection(tracks[d.family as 'navigate'|'essential'],selectedTrack(d.track,d.family));await db('school_users','PATCH',trackFields(tracks),`id=eq.${encodeURIComponent(target.id)}`);break}
case 'advance':{staff(u);const rows=await db('school_users','GET',undefined,`id=eq.${encodeURIComponent(d.id)}`);const target=rows[0];if(!target||target.role!=='student')throw new AppError('Choose a student.');const tracks=tracksFromRow(target),family=bookFamily(d.book||target.book),track=tracks[family];if(d.book&&d.book!==track.book)throw new AppError('Choose an assigned book.');const b=bookById(track.book);if(!b||track.unlockedUnit>=b.units.length)throw new AppError('Last Unit reached. Choose the next book in the student profile.');tracks[family]={...track,unlockedUnit:track.unlockedUnit+1};await db('school_users','PATCH',trackFields(tracks),`id=eq.${encodeURIComponent(target.id)}`);break}
case 'assignment':case 'event':{staff(u);const gs=await db('school_groups');if(!Array.isArray(d.groups)||!d.groups.length||!d.groups.every((id:any)=>gs.some((g:any)=>g.id===id)))throw new AppError('Select the groups that should see this.');if(d.action==='assignment')await db('school_assignments',d.id?'PATCH':'POST',{title:textValue(d.title,120),body:textValue(d.text),groups:d.groups,extra:!!d.extra},d.id?`id=eq.${encodeURIComponent(d.id)}`:'');else{if(!d.at||!Number.isFinite(Date.parse(d.at)))throw new AppError('Choose an event date and time.');await db('school_events',d.id?'PATCH':'POST',{title:textValue(d.title,120),at:d.at,groups:d.groups},d.id?`id=eq.${encodeURIComponent(d.id)}`:'')}await notifyGroups(d.groups,d.action==='assignment'?'Homework / Uyga vazifa':'Event / Dars eslatmasi',d.title,d.action,String(d.id||''));break}
case 'delete':{staff(u);const t={assignment:'school_assignments',event:'school_events'}[d.kind as 'assignment'|'event'];if(!t)throw new AppError('Invalid item.');await db(t,'DELETE',undefined,`id=eq.${encodeURIComponent(d.id)}`);break}
case 'grade':{staff(u);if(!Number.isInteger(d.grade)||d.grade<0||d.grade>100||typeof d.comment!=='string'||d.comment.length>2000)throw new AppError('Grade must be 0–100.');const rows=await db('school_attempts','GET',undefined,`id=eq.${encodeURIComponent(d.id)}`);if(!rows[0])throw new AppError('Attempt not found.');await db('school_attempts','PATCH',{grade:d.grade,comment:d.comment},`id=eq.${encodeURIComponent(d.id)}`);await notify(rows[0].user_id,'New grade / Yangi baho',`${rows[0].lesson}: ${d.grade}/100. ${d.comment}`,'grade',d.id);break}
case 'admin':{teacher(u);const rows=await db('school_users','GET',undefined,`id=eq.${encodeURIComponent(d.id)}`);if(!rows[0]||!['student','admin'].includes(rows[0].role))throw new AppError('Choose a student or admin.');await db('school_users','PATCH',{role:d.enabled?'admin':'student'},`id=eq.${d.id}`);break}
case 'resignAdministrator':{administrator(u);if(!u.temporaryAdministrator||!await resignTemporaryAdministrator(u.id))throw new AppError('Only your temporary Administrator role can be removed here.',403);break}
case 'resign':{if(u.role!=='admin')throw new AppError('Admin access required.',403);await db('school_users','PATCH',{role:'student'},`id=eq.${u.id}`);break}
case 'password':{teacher(u);const rows=await db('school_users','GET',undefined,`id=eq.${encodeURIComponent(d.id)}`);if(!rows[0]||!['student','admin'].includes(rows[0].role))throw new AppError('Choose a student or admin.');const {hashPassword}=await import('@/lib/school-server');const p=textValue(d.password,128);if(p.length<8)throw new AppError('Use at least 8 characters.');await db('school_users','PATCH',{password_hash:hashPassword(p)},`id=eq.${encodeURIComponent(d.id)}`);await db('school_sessions','DELETE',undefined,`user_id=eq.${encodeURIComponent(d.id)}`);break}
case 'push':{const s=d.subscription;if(!s?.endpoint?.startsWith('https://')||!s.keys?.p256dh||!s.keys?.auth||JSON.stringify(s).length>5000)throw new AppError('Invalid notification subscription.');await db('school_push','DELETE',undefined,`user_id=eq.${u.id}&endpoint=eq.${encodeURIComponent(s.endpoint)}`);await db('school_push','POST',{user_id:u.id,endpoint:s.endpoint,subscription:s});break}
case 'unpush':{await db('school_push','DELETE',undefined,`user_id=eq.${u.id}`);break}
default:throw new AppError('Unknown action.')}
return Response.json({ok:true},{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}})}
