'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {modeHeaders} from '@/lib/client-mode';
import {say,stopVoice} from './journey';
type Stage={title:string;stageId?:string;prompt?:string;image?:string;text?:string;prepareSeconds?:number;speakSeconds?:number};
export function StagedSpeaking({attempt,stages,center,uz,request,onClips,onWorking,onComplete}:{attempt:any;stages:Stage[];center:string;uz:boolean;request:(d:any)=>Promise<any>;onClips:(clips:any[])=>void;onWorking:(v:boolean)=>void;onComplete:()=>void}){
 const t=(en:string,u:string)=>uz?u:en,[phase,setPhase]=useState('idle'),[index,setIndex]=useState(0),[left,setLeft]=useState(0),[error,setError]=useState('');
 const alive=useRef(true),running=useRef(false),media=useRef<MediaStream|null>(null),recorder=useRef<MediaRecorder|null>(null),clips=useRef<any[]>(attempt.clips||[]),pending=useRef<any>(null);
 const key='lingora-speaking-pending|'+attempt.id;
 useEffect(()=>{alive.current=true;try{pending.current=JSON.parse(localStorage.getItem(key)||'null')}catch{}return()=>{alive.current=false;running.current=false;stopVoice();if(recorder.current?.state==='recording')recorder.current.stop();media.current?.getTracks().forEach(x=>x.stop());onWorking(false)}},[attempt.id]);
 useEffect(()=>{clips.current=attempt.clips||[]},[attempt.clips]);
 async function wait(seconds:number){const until=Date.now()+seconds*1000;while(alive.current&&Date.now()<until){setLeft(Math.ceil((until-Date.now())/1000));await new Promise(r=>setTimeout(r,200))}if(!alive.current)throw Error('Interrupted');setLeft(0)}
 async function prompt(text:string){setPhase('prompt');await new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>{stopVoice();reject(Error(t('The question audio could not finish. Start again to hear this question.','Savol ovozi tugamadi. Shu savolni eshitish uchun qayta boshlang.')))},90000);say(text,.9,'en',(voiceError)=>{clearTimeout(timeout);if(voiceError)reject(voiceError);else resolve()},true).catch(e=>{clearTimeout(timeout);reject(e)})});if(!alive.current)throw Error('Interrupted')}
 async function capture(seconds:number){const s=media.current!;const mime=['audio/webm','audio/mp4','audio/ogg'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime)throw Error(t('This browser cannot record audio. Try Chrome or Edge.','Bu brauzer ovoz yozolmaydi. Chrome yoki Edge ishlating.'));
  const blob=await new Promise<Blob>((resolve,reject)=>{const chunks:Blob[]=[],r=new MediaRecorder(s,{mimeType:mime,audioBitsPerSecond:24000});recorder.current=r;const until=Date.now()+seconds*1000;let timer:ReturnType<typeof setInterval>;r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};r.onerror=()=>{clearInterval(timer);reject(Error(t('Recording failed. Please try again.','Ovozni yozib bo‘lmadi. Qayta urinib ko‘ring.')))};r.onstop=()=>{clearInterval(timer);resolve(new Blob(chunks,{type:mime}))};r.start();timer=setInterval(()=>{if(!alive.current||Date.now()>=until){if(r.state==='recording')r.stop()}else setLeft(Math.ceil((until-Date.now())/1000))},200);setLeft(seconds);setPhase('record')});
  if(!alive.current)throw Error('Interrupted');if(!blob.size||blob.size>600000)throw Error(t('Empty or oversized recording. Please repeat this question.','Ovoz bo‘sh yoki juda katta. Shu savolni qayta bajaring.'));
  const data=await new Promise<string>((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(String(f.result).split(',')[1]);f.onerror=reject;f.readAsDataURL(blob)});return{mime,data};
 }
 async function save(stageId:string,recording:any){setPhase('save');pending.current={stageId,recording};try{localStorage.setItem(key,JSON.stringify(pending.current))}catch{}const d=await request({action:'clip',id:attempt.id,stageId,recording});clips.current=[...clips.current.filter(c=>c.stage_id!==stageId),d.clip];if(alive.current)onClips(clips.current);pending.current=null;try{localStorage.removeItem(key)}catch{}}
 async function start(){if(running.current)return;running.current=true;onWorking(true);setError('');try{
  if(pending.current)await save(pending.current.stageId,pending.current.recording);
  if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error(t('Allow the microphone on HTTPS or localhost.','HTTPS yoki localhostda mikrofonga ruxsat bering.'));
  media.current=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){media.current.getTracks().forEach(x=>x.stop());return}
  for(let i=0;i<stages.length;i++){const g=stages[i];if(clips.current.some(c=>c.stage_id===g.stageId))continue;if(Date.now()>=Date.parse(attempt.deadline))break;setIndex(i);await prompt(g.prompt!);if(g.prepareSeconds){setPhase('prepare');await wait(g.prepareSeconds)}const seconds=Math.max(1,Math.min(g.speakSeconds!,Math.floor((Date.parse(attempt.deadline)-Date.now())/1000)));const recording=await capture(seconds);await save(g.stageId!,recording)}
  setPhase('done');onWorking(false);onComplete();
 }catch(e){if(alive.current){setError((e as Error).message);setPhase('idle')}}finally{running.current=false;media.current?.getTracks().forEach(x=>x.stop());onWorking(false)}}
 const finished=attempt.state==='completed',g=stages[index],working=!['idle','done'].includes(phase);
 return <div className="exam-speaking">
 {!finished&&<><p>{t('After you start, each question is read aloud. Preparation and recording timers run automatically. The microphone stops when the answer time ends. Completed answers are saved separately.','Boshlagandan so‘ng har savol ovozli beriladi. Tayyorgarlik va yozish vaqti avtomatik ishlaydi. Vaqt tugaganda mikrofon o‘chadi. Tugagan javoblar alohida saqlanadi.')}</p><progress max={stages.length} value={attempt.clips?.length||0}/><p>{attempt.clips?.length||0} / {stages.length} {t('answers saved','javob saqlandi')}</p>
 {working&&g&&<article className="exam-group" aria-live="polite"><h3>{g.title}</h3>{g.image&&<img className="exam-illustration" src={g.image} alt={t('Speaking prompt illustration','Speaking savoli rasmi')}/>}<p>{g.prompt}</p>{g.text&&<p className="exam-passage">{g.text}</p>}<strong>{phase==='prompt'?t('Listen to the question','Savolni tinglang'):phase==='prepare'?t('Prepare your answer','Javobga tayyorlaning'):phase==='record'?t('Speak now · recording','Gapiring · ovoz yozilmoqda'):t('Saving your answer…','Javob saqlanmoqda…')} {['prepare','record'].includes(phase)&&' · '+left+'s'}</strong>{phase==='record'&&<span className="exam-record-dot"/>}</article>}
 {error&&<p className="exam-error" role="alert">{error}</p>}<Button disabled={working} onClick={start}>{working?t('Test in progress','Sinov davom etmoqda'):attempt.clips?.length||pending.current?t('Continue speaking','Speakingni davom ettirish'):t('Start speaking test','Speaking sinovini boshlash')}</Button></>}
 {!!attempt.clips?.length&&<details open={finished}><summary>{t('Saved answers','Saqlangan javoblar')}</summary>{attempt.clips.map((c:any)=><div className="exam-clip" key={c.stage_id}><strong>{stages.find(g=>g.stageId===c.stage_id)?.title||c.stage_id}</strong><PrivateClip id={attempt.id} stage={c.stage_id} center={center} uz={uz}/></div>)}</details>}
 </div>
}
function PrivateClip({id,stage,center,uz}:{id:string;stage:string;center:string;uz:boolean}){const [url,setUrl]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),ref=useRef('');useEffect(()=>()=>{if(ref.current)URL.revokeObjectURL(ref.current)},[]);async function load(){setBusy(true);setError('');try{const r=await fetch('/api/exams?center='+encodeURIComponent(center)+'&subject=english&id='+encodeURIComponent(id)+'&clip='+encodeURIComponent(stage),{headers:modeHeaders(),signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error(uz?'Ovozni ochib bo‘lmadi.':'Could not load recording.');ref.current=URL.createObjectURL(await r.blob());setUrl(ref.current)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <>{url?<audio controls src={url}/>:<Button variant="outline" disabled={busy} onClick={load}>{busy?'…':uz?'Javobni eshitish':'Listen to answer'}</Button>}{error&&<span role="alert">{error}</span>}</>}
