'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import type {ExamPack} from '@/lib/exams';
export function ExamEditor({packs,onPublish,onCancel,uz}:{packs:ExamPack[];onPublish:(title:string,packs:ExamPack[])=>Promise<void>;onCancel:()=>void;uz:boolean}){
 const [draft,setDraft]=useState(()=>structuredClone(packs)),[title,setTitle]=useState(''),[skill,setSkill]=useState(0),[part,setPart]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const t=(a:string,b:string)=>uz?b:a,p=draft[skill],g=p.groups[part];
 function change(fn:(copy:ExamPack[])=>void){setDraft(prev=>{const copy=structuredClone(prev);fn(copy);return copy})}
 const field=(key:'text'|'script'|'prompt')=>g[key]!==undefined&&<label>{key==='script'?t('Audio script (spoken by the selected voice)','Audio matni (tanlangan ovozda o‘qiladi)'):key==='prompt'?t('Examiner prompt','Speaking savoli'):t('Reading / task text','O‘qish / topshiriq matni')}<textarea rows={8} maxLength={30000} value={g[key]} onChange={e=>change(c=>{c[skill].groups[part][key]=e.target.value})}/></label>;
 return <div className="exam-editor"><h3>{t('Create a centre test','Markaz testini yaratish')}</h3><p>{t('Replace the template texts, prompts and answer keys. Published papers cannot be edited; publish a new version and archive the old one. Existing student results stay intact.','Namuna matnlari, savollari va javoblarini almashtiring. Chop etilgan variant o‘zgartirilmaydi: yangi variant chiqaring, eskisini arxivlang. O‘quvchilar natijalari saqlanadi.')}</p><label>{t('Test name','Test nomi')}<input value={title} maxLength={120} onChange={e=>setTitle(e.target.value)} placeholder="Zamon · Mock 2"/></label><div className="exam-part-nav">{draft.map((p,i)=><button key={p.skill} className={skill===i?'active':''} onClick={()=>{setSkill(i);setPart(0)}}>{p.skill}</button>)}</div><label>{t('Part / question','Qism / savol')}<select value={part} onChange={e=>setPart(Number(e.target.value))}>{p.groups.map((g,i)=><option key={i} value={i}>{i+1}. {g.title}</option>)}</select></label><label>{t('Part title','Qism nomi')}<input value={g.title} onChange={e=>change(c=>{c[skill].groups[part].title=e.target.value})}/></label>{field('text')}{field('script')}{field('prompt')}{g.image&&<><img className="exam-illustration" src={g.image} alt="Template diagram"/><p>{t('Keep questions consistent with this template diagram.','Savollar namuna chizmasiga mos bo‘lsin.')}</p></>}
 {g.questions?.map((q,j)=><div className="exam-question" key={q.id}><label>{q.id}. {t('Question','Savol')}<textarea rows={2} value={q.prompt} onChange={e=>change(c=>{c[skill].groups[part].questions![j].prompt=e.target.value})}/></label>{['reading','listening'].includes(p.skill)&&<><label>{t('Correct answers (one per line)','To‘g‘ri javoblar (har qatorda bittadan)')}<textarea rows={2} value={q.accepted.join('\n')} onChange={e=>change(c=>{c[skill].groups[part].questions![j].accepted=e.target.value.split('\n')})}/></label><label>{t('Options (one per line; leave empty for typed answers)','Variantlar (har qatorda bittadan; yozma javob uchun bo‘sh qoldiring)')}<textarea rows={3} value={q.options?.join('\n')||''} onChange={e=>change(c=>{c[skill].groups[part].questions![j].options=e.target.value?e.target.value.split('\n'):undefined})}/></label></>}</div>)}
 <p>{t('Check all four skills and every answer before publishing. Use only materials you have permission to share.','Chop etishdan oldin to‘rt bo‘lim va barcha javoblarni tekshiring. Ulashishga ruxsatingiz bor materiallardan foydalaning.')}</p>{error&&<p role="alert" className="exam-error">{error}</p>}<div className="exam-start-row"><Button disabled={busy||title.trim().length<3} onClick={async()=>{setBusy(true);setError('');try{await onPublish(title,draft)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?t('Saving…','Saqlanmoqda…'):t('Publish to this centre','Shu markazga chop etish')}</Button><Button variant="outline" disabled={busy} onClick={onCancel}>{t('Cancel','Bekor qilish')}</Button></div></div>
}
