'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {modeHeaders} from '@/lib/client-mode';
const cached=new Map<string,string>();
export function Translator({uz,onNote}:{uz:boolean;onNote:(text:string)=>void}){
 const t=(a:string,b:string)=>uz?b:a;const [input,setInput]=useState(''),[source,setSource]=useState('en'),[target,setTarget]=useState('uz'),[output,setOutput]=useState(''),[details,setDetails]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const sequence=useRef(0),controller=useRef<AbortController|null>(null);
 async function translate(more=false){const text=input.trim(),seq=++sequence.current;controller.current?.abort();if(!text){setOutput('');setDetails('');setBusy(false);return}const key=JSON.stringify([modeHeaders(),source,target,text,more]);setError('');if(cached.has(key)){(more?setDetails:setOutput)(cached.get(key)!);setBusy(false);return}const c=new AbortController();controller.current=c;setBusy(true);try{const r=await fetch('/api/learning',{method:'POST',headers:{'Content-Type':'application/json',...modeHeaders()},signal:AbortSignal.any([c.signal,AbortSignal.timeout(30000)]),body:JSON.stringify({action:'translate',input:text,source,target,more})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Tarjima ishlamadi.');if(seq!==sequence.current)return;if(cached.size>=100)cached.delete(cached.keys().next().value!);cached.set(key,data.text);(more?setDetails:setOutput)(data.text)}catch(e){if(seq===sequence.current&&(e as Error).name!=='AbortError')setError((e as Error).name==='TimeoutError'?'Tarjima javobini kutish vaqti tugadi. Qayta urinib ko‘ring.':(e as Error).message)}finally{if(seq===sequence.current)setBusy(false)}}
 useEffect(()=>{sequence.current++;controller.current?.abort();setOutput('');setDetails('');setBusy(false);const timer=setTimeout(()=>void translate(),400);return()=>{clearTimeout(timer);controller.current?.abort()}},[input,source,target]);
 return <section className="translator-panel"><h2>{t('Translator','Tarjimon')}</h2><div className="translator-languages"><select aria-label={t('Source language','Asl til')} value={source} onChange={e=>{setSource(e.target.value);setTarget(e.target.value==='en'?'uz':'en')}}><option value="en">English</option><option value="uz">O‘zbekcha</option></select><Button variant="outline" aria-label={t('Swap languages','Tillarni almashtirish')} onClick={()=>{setSource(target);setTarget(source);setInput(output)}}>⇄</Button><strong>{target==='en'?'English':'O‘zbekcha'}</strong></div><div className="translator-columns"><label>{t('Text','Matn')}<textarea rows={5} maxLength={1000} value={input} onChange={e=>setInput(e.target.value)} placeholder={t('Enter a word or sentence…','So‘z yoki gap yozing…')}/></label><div><span>{t('Translation','Tarjima')}</span><article className="translation-output preserve" aria-live="polite">{output|| (busy?t('Translating…','Tarjima qilinmoqda…'):t('Translation appears here','Tarjima shu yerda chiqadi'))}</article></div></div><div className="actions"><Button disabled={busy||!input.trim()} onClick={()=>void translate()}>{t('Translate','Tarjima')}</Button><Button variant="outline" disabled={busy||!input.trim()} onClick={()=>void translate(true)}>{t('More','Ko‘proq')}</Button>{output&&<Button variant="outline" onClick={()=>onNote([input,output,details].filter(Boolean).join('\n\n'))}>{t('Add to note','Notega qo‘shish')}</Button>}</div>{details&&<article className="assignment preserve">{details}</article>}{error&&<p role="alert" className="error">{error}</p>}</section>
}
