'use client';
import {Translator} from './translator';
import {modeHeaders} from '@/lib/client-mode';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
export async function learning(data?:any,url='/api/learning'){const r=await fetch(url,{method:data?'POST':'GET',headers:{...(data?{'Content-Type':'application/json'}:{}),...modeHeaders(),...(typeof window!=='undefined'&&localStorage.getItem('owner-center')?{'X-Center-ID':localStorage.getItem('owner-center')!}:{})},body:data?JSON.stringify(data):undefined,cache:'no-store'});const v=await r.json();if(!r.ok)throw new Error(v.error||'Please retry.');return v;}
export function Workspace({student,teacher=false,readOnly=false,uz=false,questionsOnly=false}:{student?:string;teacher?:boolean;readOnly?:boolean;uz?:boolean;questionsOnly?:boolean}){
 const [data,setData]=useState<any>({notes:[],questions:[]}),[body,setBody]=useState(''),[id,setId]=useState(''),[input,setInput]=useState(''),[translation,setTranslation]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const t=(a:string,b:string)=>uz?b:a;
 async function reload(){try{setError('');setData(await learning(undefined,'/api/learning?action=workspace'+(student?'&student='+encodeURIComponent(student):'')))}catch(e){setError((e as Error).message)}}
 useEffect(()=>{reload()},[student]);
 async function run(f:()=>Promise<void>){setBusy(true);setError('');try{await f()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className={"learning-workspace"+(questionsOnly?" questions-page":"")}>{!readOnly&&!teacher&&!questionsOnly&&<><Translator uz={uz} onNote={text=>setBody(prev=>[prev,text].filter(Boolean).join('\n\n'))}/><h2>{t('My vocabulary notes','Lug‘at daftarim')}</h2>{error&&<p role="alert" className="error">{error}<Button variant="outline" onClick={()=>reload()}>{t('Retry loading notes','Notelarni qayta yuklash')}</Button></p>}<p className="muted">{t('Your assigned teacher and Administrator can read these notes.','Yozuvlaringizni o‘z o‘qituvchingiz va Administrator ko‘ra oladi.')}</p><textarea rows={6} value={body} maxLength={12000} onChange={e=>setBody(e.target.value)} placeholder={t('Words, meanings, examples and reminders…','So‘zlar, ma’nolari, misollar va eslatmalar…')}/><div className="actions"><Button disabled={busy||!body.trim()} onClick={()=>run(async()=>{await learning({action:'note',id:id||undefined,body});setBody('');setId('');await reload()})}>{t('Save note','Noteni saqlash')}</Button>{id&&<Button variant="outline" onClick={()=>{setId('');setBody('')}}>{t('Cancel edit','Bekor qilish')}</Button>}</div></>}{!teacher&&!questionsOnly&&data.notes.map((n:any)=><article className="assignment" key={n.id}><p className="preserve">{n.body}</p><small>{new Date(n.updated_at).toLocaleString()}</small>{!readOnly&&<div className="actions"><Button variant="outline" onClick={()=>{setId(n.id);setBody(n.body)}}>{t('Edit','Tahrirlash')}</Button><Button variant="outline" disabled={busy} onClick={()=>run(async()=>{if(confirm(t('Delete this note?','Noteni o‘chirasizmi?'))){await learning({action:'deleteNote',id:n.id});await reload()}})}>{t('Delete','O‘chirish')}</Button></div>}</article>)}{(questionsOnly||teacher||readOnly)&&<>{error&&<p role="alert" className="error">{error}</p>}{questionsOnly&&!teacher&&<AskTeacher book="" unit={0} lesson="" uz={uz} inline onSent={reload}/>}<h2>{t('Questions and replies','Savollar va javoblar')}</h2>{!data.questions.length&&<p>{t('No questions yet.','Hali savollar yo‘q.')}</p>}{data.questions.map((q:any)=><article className="assignment" key={q.id}><small>{q.book} · Unit {q.unit} · {q.lesson}</small><p className="preserve">{q.body}</p>{q.reply?<p className="teacher-reply">{q.reply}</p>:<p className="muted">{t('Awaiting teacher reply','O‘qituvchi javobi kutilmoqda')}</p>}{teacher&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await learning({action:'reply',id:q.id,body:f.get('body')});await reload()})}}><textarea name="body" required maxLength={4000} rows={3} defaultValue={q.reply}/><Button disabled={busy} type="submit">{t('Reply','Javob berish')}</Button></form>}</article>)}</>}</section>
}
export function AskTeacher({book,unit,lesson,uz=false,inline=false,onSent}:{book:string;unit:number;lesson:string;uz?:boolean;inline?:boolean;onSent?:()=>Promise<void>}){const [body,setBody]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);const content=<><p>{uz?'Savol o‘z o‘qituvchingizga yuboriladi.':'Your question is sent to your assigned teacher.'}</p><textarea aria-label={uz?'Savolingizni yozing':'Write your question'} placeholder={uz?'Savolingizni shu yerga yozing…':'Write your question here…'} value={body} onChange={e=>setBody(e.target.value)} maxLength={3000} rows={5}/><Button disabled={busy||!body.trim()} onClick={async()=>{setBusy(true);setStatus('');try{await learning({action:'question',book,unit,lesson,body});setBody('');setStatus(uz?'Yuborildi':'Sent');await onSent?.()}catch(e){setStatus((e as Error).message)}finally{setBusy(false)}}}>{busy?(uz?'Yuborilmoqda…':'Sending…'):uz?'Yuborish':'Send'}</Button><p role="status">{status}</p></>;return inline?<div className="question-compose">{content}</div>:<details className="ask-teacher"><summary>{uz?'O‘qituvchiga savol':'Ask your teacher'}</summary>{content}</details>}
