import {randomUUID} from 'node:crypto';
import {schoolScope} from '@/lib/center-context';
import {current,db,AppError,fail,mutation,digest,claimExamWindow} from '@/lib/school-server';
import {selectCourse,groupsFor,q} from '@/lib/courses-server';
import {exams,publicPack,questions,gradeObjective,sources} from '@/lib/exams';
import {validateSuite} from '@/lib/exams/custom';
import {examCertificate} from '@/lib/exams/certificate';
import {sectionPracticeScore,overallPracticeScore} from '@/lib/exams/results';
import type {User} from '@/lib/school-types';
export const runtime='nodejs';
async function context(req:Request){const u=await current(req),p=new URL(req.url).searchParams,center=p.get('center')||u.centerId;const subject=p.get('subject')||'english';if(subject!=='english')throw new AppError('IELTS / CEFR English bo‘limida mavjud.',403);await selectCourse(u,center,subject);return{u,p,center}}
async function visible(u:User){const rows=await db('school_exam_attempts','GET',undefined,'subject_id=eq.english');if(['owner','administrator'].includes(u.role))return rows;if(['teacher','admin'].includes(u.role)){const groups=new Set((await groupsFor(u)).map((g:any)=>g.id)),members=new Set((await db('school_users')).filter((s:any)=>groups.has(s.group_id)).map((s:any)=>s.id));return rows.filter((r:any)=>r.user_id===u.id||members.has(r.user_id))}return rows.filter((r:any)=>r.user_id===u.id)}
const summary=(r:any)=>{const {recording,answers,review,...s}=r;return s};
const clipSummary=(r:any)=>{const {data,...s}=r;return s};
async function withClips(row:any,bank=exams){if(!bank.find(p=>p.id===row.pack_id)?.stagedSpeaking)return row;const clips=await db('school_exam_clips','GET',undefined,'attempt_id=eq.'+row.id);return {...row,clips:clips.map(clipSummary)}}
async function examBank():Promise<typeof exams>{const suites=await db('school_exam_suites');return [...exams,...suites.flatMap((s:any)=>s.packs.map((p:any)=>({...p,available:!s.archived})))];}
const author=(u:User)=>['teacher','administrator','owner'].includes(u.role);
function validRecording(r:any){return r&&['audio/webm','audio/ogg','audio/mp4'].includes(r.mime)&&typeof r.data==='string'&&r.data.length>0&&r.data.length<=800000&&/^[A-Za-z0-9+/]+={0,2}$/.test(r.data)}
function answerValues(value:unknown,ids:string[]){if(!value||typeof value!=='object'||Array.isArray(value))throw new AppError('Javoblar noto‘g‘ri.');const result:Record<string,string>={};for(const id of ids){const v=(value as any)[id]??'';if(typeof v!=='string'||v.length>10000)throw new AppError('Javob juda uzun.');result[id]=v}return result}
export async function GET(req:Request){return schoolScope(async()=>{try{const {u,p,center}=await context(req);const bank=await examBank(),rows=await visible(u);
if(p.get('template')){if(!author(u))throw new AppError('Test yaratishga ruxsat yo‘q.',403);return Response.json({packs:exams.filter(x=>x.fullLength&&x.exam===p.get('template'))},{headers:{'Cache-Control':'no-store'}});}
if(p.get('certificate')){const selected=rows.filter((r:any)=>r.session_id===p.get('certificate'));if(!selected.length)throw new AppError('Sertifikat topilmadi.',404);const first=selected[0];if(selected.some((r:any)=>r.user_id!==first.user_id||r.exam!==first.exam||r.suite_id!==first.suite_id)||new Set(selected.map((r:any)=>r.skill)).size!==4||selected.length!==4)throw new AppError('To‘rt bo‘limni bir sessiyada tugating.',409);const overall=overallPracticeScore(first.exam,selected);if(overall===null)throw new AppError('Writing va Speaking baholanishini kuting.',409);const member=(await db('school_users')).find((m:any)=>m.id===first.user_id);if(!member)throw new AppError('O‘quvchi topilmadi.',404);const c=(await db('school_centers')).find((c:any)=>c.id===center);const issued=selected.map((r:any)=>r.graded_at||r.completed_at).sort().at(-1);const id='LG-'+digest(first.user_id+'|'+first.session_id).slice(0,20).toUpperCase();const bytes=await examCertificate({id,name:member.first_name+' '+member.last_name,center:c?.name||center,title:bank.find(p=>p.id===first.pack_id)?.title.replace(/ · (listening|reading|writing|speaking)$/,'')||first.title,exam:first.exam,date:issued.slice(0,10),overall,scores:['listening','reading','writing','speaking'].map(skill=>({skill,score:sectionPracticeScore(selected.find((r:any)=>r.skill===skill))!}))});return new Response(Buffer.from(bytes),{headers:{'Content-Type':'application/pdf','Content-Disposition':'attachment; filename=Lingora-'+id+'.pdf','Cache-Control':'private, no-store'}});}if(p.get('id')){const row=rows.find((r:any)=>r.id===p.get('id'));if(!row)throw new AppError('Natija topilmadi.',404);if(p.get('clip')){const clip=(await db('school_exam_clips','GET',undefined,'attempt_id=eq.'+row.id)).find((c:any)=>c.stage_id===p.get('clip'));if(!clip)throw new AppError('Ovoz topilmadi.',404);return new Response(Buffer.from(clip.data,'base64'),{headers:{'Content-Type':clip.mime,'Cache-Control':'private, no-store'}})}return Response.json({attempt:await withClips(row,bank)},{headers:{'Cache-Control':'no-store'}})}const members=await db('school_users');return Response.json({catalog:bank.map(publicPack),sources,windows:(await db('school_exam_windows')).filter((w:any)=>w.user_id===u.id).map((w:any)=>({exam:w.exam,next_at:w.next_at,session_id:w.session_id,suite_id:w.suite_id})),suites:(await db('school_exam_suites')).map((s:any)=>({id:s.id,title:s.title,exam:s.exam,archived:!!s.archived})),attempts:rows.sort((a:any,b:any)=>b.created_at.localeCompare(a.created_at)).slice(0,100).map(summary),names:Object.fromEntries(members.filter((m:any)=>rows.some((r:any)=>r.user_id===m.id)).map((m:any)=>[m.id,m.first_name+' '+m.last_name]))},{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}})}
export async function POST(req:Request){return schoolScope(async()=>{try{mutation(req);const {u,center}=await context(req);const body=await req.text();if(body.length>1000000)throw new AppError('Ovoz yoki javob juda katta.',413);let d:any;try{d=JSON.parse(body)}catch{throw new AppError('So‘rov noto‘g‘ri.')}const bank=await examBank();if(d.action==='publish'){if(!author(u))throw new AppError('Faqat o‘qituvchi, Administrator yoki Owner test qo‘sha oladi.',403);if(typeof d.title!=='string'||d.title.trim().length<3||d.title.length>120)throw new AppError('Test nomini yozing.');const id='centre-'+randomUUID();let packs;try{packs=validateSuite(d.packs,id,d.title.trim())}catch(e){throw new AppError((e as Error).message)}const suite={id,center_id:center,subject_id:'english',title:d.title.trim(),exam:packs[0].exam,packs,created_by:u.id,created_at:new Date().toISOString(),archived:false};await db('school_exam_suites','POST',suite);return Response.json({suite:{id,title:suite.title,exam:suite.exam}});}
if(d.action==='archive'){if(!author(u))throw new AppError('Ruxsat yo‘q.',403);const suite=(await db('school_exam_suites','GET',undefined,q(d.suiteId)))[0];if(!suite)throw new AppError('Test topilmadi.',404);await db('school_exam_suites','PATCH',{archived:true},q(suite.id));return Response.json({ok:true});}
if(d.action==='start'){const pack=bank.find(p=>p.id===d.packId);if(!pack)throw new AppError('Test topilmadi.',404);if(typeof d.key!=='string'||!/^[-a-zA-Z0-9]{16,100}$/.test(d.key))throw new AppError('Testni qayta oching.');const sessionId=pack.fullLength?(d.sessionId||d.key):undefined;const id=digest(u.id+'|exam|'+center+'|'+(sessionId?sessionId+'|'+pack.skill:d.key));const old=(await db('school_exam_attempts','GET',undefined,q(id)))[0];if(old)return Response.json({attempt:old});if(d.sessionId!==undefined&&(!pack.fullLength||typeof d.sessionId!=='string'||!/^[-a-zA-Z0-9]{16,100}$/.test(d.sessionId)))throw new AppError('Imtihon sessiyasi noto‘g‘ri.');if(pack.fullLength){if(pack.available===false&&!(await db('school_exam_attempts')).some((a:any)=>a.user_id===u.id&&a.session_id===sessionId&&a.suite_id===pack.suiteId))throw new AppError('Test arxivlangan.',409);await claimExamWindow({user_id:u.id,exam:pack.exam,center_id:center,session_id:sessionId,suite_id:pack.suiteId||'lingora-'+pack.exam});}const now=new Date();const row={id,center_id:center,subject_id:'english',user_id:u.id,group_id:u.groupId,pack_id:pack.id,title:pack.title,exam:pack.exam,skill:pack.skill,state:'in-progress',created_at:now.toISOString(),deadline:new Date(now.getTime()+pack.minutes*60000).toISOString(),answers:{},recording:null,score:null,total:questions(pack).length,grade:null,comment:'',...(sessionId?{session_id:sessionId,suite_id:pack.suiteId||'lingora-'+pack.exam}:{})};await db('school_exam_attempts','POST',row);return Response.json({attempt:row})}
 const row=(await visible(u)).find((r:any)=>r.id===d.id);if(!row)throw new AppError('Natijaga ruxsat yo‘q.',403);const pack=bank.find(p=>p.id===row.pack_id);if(!pack)throw new AppError('Test topilmadi.',404);
 if(d.action==='grade'){if(!['teacher','admin','owner','administrator'].includes(u.role)||row.state!=='completed'||!['writing','speaking'].includes(row.skill))throw new AppError('Bu natijani baholashga ruxsat yo‘q.',403);const max=row.exam==='ielts'?9:pack.fullLength?75:100;if(typeof d.grade!=='number'||!Number.isFinite(d.grade)||d.grade<0||d.grade>max||row.exam==='ielts'&&d.grade*2!==Math.round(d.grade*2))throw new AppError('Bahoni tekshiring.');if(typeof d.comment!=='string'||d.comment.trim().length<3||d.comment.length>3000)throw new AppError('Bahoga izoh yozing.');const patch={grade:d.grade,comment:d.comment.trim(),graded_by:u.id,graded_at:new Date().toISOString()};await db('school_exam_attempts','PATCH',patch,q(row.id));try{const {notify}=await import('@/lib/notifications-server');await notify(row.user_id,'IELTS / CEFR · Baho',row.title+': '+d.grade+' — '+patch.comment,'exam',row.id)}catch{console.error('Exam grade saved; notification delivery failed.')}return Response.json({attempt:await withClips({...row,...patch},bank)})}
 if(row.user_id!==u.id)throw new AppError('Faqat o‘z javobingizni yuboring.',403);
 if(d.action==='clip'){if(!pack.stagedSpeaking||row.state!=='in-progress')throw new AppError('Ovoz yozishga ruxsat yo‘q.',409);const stage=pack.groups.find(g=>g.stageId===d.stageId);if(!stage||!validRecording(d.recording))throw new AppError('Ovoz yoki savol noto‘g‘ri.');const id=digest(row.id+'|clip|'+d.stageId);const old=(await db('school_exam_clips','GET',undefined,q(id)))[0];if(old)return Response.json({clip:clipSummary(old)});if(Date.now()>Date.parse(row.deadline)+15000)throw new AppError('Speaking vaqti tugadi.',409);const earlier=pack.groups.slice(0,pack.groups.indexOf(stage)),saved=await db('school_exam_clips','GET',undefined,'attempt_id=eq.'+row.id);if(earlier.some(g=>!saved.some((c:any)=>c.stage_id===g.stageId)))throw new AppError('Savollarni ketma-ket bajaring.',409);const clip={id,attempt_id:row.id,stage_id:d.stageId,center_id:row.center_id,subject_id:'english',user_id:u.id,mime:d.recording.mime,data:d.recording.data,created_at:new Date().toISOString()};await db('school_exam_clips','POST',clip);return Response.json({clip:clipSummary(clip)})}
if(row.state==='completed'){if(d.action==='submit')return Response.json({attempt:row});throw new AppError('Topshirilgan javobni o‘zgartirib bo‘lmaydi.',409)}if(!['save','submit'].includes(d.action))throw new AppError('Amal topilmadi.');const answers=answerValues(d.answers,questions(pack).map(q=>q.id));let recording=row.recording;if(d.recording!==undefined){if(d.recording!==null&&(!['audio/webm','audio/ogg','audio/mp4'].includes(d.recording?.mime)||typeof d.recording?.data!=='string'||d.recording.data.length>800000||!d.recording.data.length||!/^[A-Za-z0-9+/]+={0,2}$/.test(d.recording.data)))throw new AppError('Ovoz fayli noto‘g‘ri yoki juda katta.');if(pack.skill!=='speaking'&&d.recording)throw new AppError('Bu bo‘limda ovoz yuborilmaydi.');recording=d.recording}
 const expired=Date.now()>Date.parse(row.deadline);if(d.action==='save'&&expired)throw new AppError('Vaqt tugadi. Javoblarni topshiring.',409);const objective=['reading','listening'].includes(pack.skill);const patch:any={answers,recording,updated_at:new Date().toISOString()};if(d.action==='submit'){if(pack.stagedSpeaking){const clips=await db('school_exam_clips','GET',undefined,'attempt_id=eq.'+row.id);if(!clips.length||(!expired&&clips.length<pack.groups.length))throw new AppError('Speaking savollarini tugating.');patch.clip_count=clips.length}else if(pack.skill==='speaking'&&!recording)throw new AppError('Avval ovozingizni yozib oling.');Object.assign(patch,{state:'completed',completed_at:new Date().toISOString(),timed_out:expired,...(objective?gradeObjective(pack,answers):{score:null,total:questions(pack).length,review:[]})})}await db('school_exam_attempts','PATCH',patch,q(row.id));return Response.json({attempt:await withClips({...row,...patch},bank)})}catch(e){return fail(e)}})}
