import {subjects,courseCodeHash} from '@/lib/courses-server';
import {reserveTeacherCode,checkTeacherCode} from '@/lib/teacher-access-code';
import {selectedTracks,trackFields} from '@/lib/study-tracks-server';
import {randomBytes,createHmac,timingSafeEqual} from 'node:crypto';
import {AppError,ownerSession,activateTeacher,claimPendingTeacher,createAdministrator,db,digest,fail,hashPassword,mutation,safeUser,textValue,verifyPassword} from '@/lib/school-server';
import {centerContext,legacyCenter,schoolScope} from '@/lib/center-context';
import {requiredLessons} from '@/lib/lessons';
import {books} from '@/lib/catalog';
export const runtime='nodejs';
function equal(a:string,b:string){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)}
function secure(req:Request){return req.headers.get('x-forwarded-proto')==='https'||new URL(req.url).protocol==='https:'?'; Secure':''}
function signature(value:string){const secret=process.env.OWNER_ACCESS_CODE||process.env.TEACHER_ACCESS_CODE||process.env.ADVERTISER_ACCESS_CODE;if(!secret)throw new AppError('Registration is not configured.',503);return createHmac('sha256',secret).update(value).digest('hex')}
async function center(id:string){if(id===legacyCenter)return{id,name:'Zamon'};const rows=await db('school_centers','GET',undefined,`id=eq.${encodeURIComponent(id)}`);if(!rows[0]||rows[0].disabled)throw new AppError('Choose an available learning centre.');return rows[0]}
function cookie(req:Request,name:string){return req.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='))?.slice(name.length+1)||''}
async function signIn(req:Request,r:any){
 const token=randomBytes(32).toString('hex'),session={token:digest(token),user_id:r.id,expires_at:new Date(Date.now()+30*864e5).toISOString()};
 const headers=new Headers({'Cache-Control':'no-store'});
 if(r.role==='owner'){
  const previous=cookie(req,'owner_device'),device=/^[a-f0-9]{64}$/.test(previous)?previous:randomBytes(32).toString('hex');
  const old=cookie(req,'school_session');await ownerSession(session,digest(device),old?digest(old):'');
  headers.append('Set-Cookie',`owner_device=${device}; HttpOnly; SameSite=Lax; Path=/; Max-Age=31536000${secure(req)}`);
 }else await db('school_sessions','POST',session);
 headers.append('Set-Cookie',`school_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000${secure(req)}`);
 return Response.json({user:safeUser(r),loggedIn:true},{headers});
}
export async function GET(){return schoolScope(async()=>{try{const rows=await db('school_centers');const centers=[{id:legacyCenter,name:'Zamon'},...rows.filter((r:any)=>!r.disabled&&r.id!==legacyCenter).map((r:any)=>({id:r.id,name:r.name}))];const definitions=await db('school_subjects'),catalog=[];for(const c of centers){const own=definitions.filter((s:any)=>s.center_id===c.id),english=own.find((s:any)=>s.subject_key==='english')||{subject_key:'english',name:'English',english:true};for(const subject of [english,...own.filter((s:any)=>s.subject_key!=='english')])if(subject.enabled!==false)catalog.push({id:subject.subject_key||subject.id,centerId:c.id,name:subject.name,english:!!subject.english,units:subject.public_units||1})};return Response.json({centers,subjects:catalog},{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}})}
export async function POST(req:Request){return schoolScope(async()=>{try{
 mutation(req);const d=await req.json();
 if(d.action==='verifyTeacherCode'){
  const code=typeof d.code==='string'?d.code.trim():'',owner=process.env.OWNER_ACCESS_CODE?.trim();
  if(owner&&[process.env.TEACHER_ACCESS_CODE?.trim(),process.env.ADMINISTRATOR_ACCESS_CODE?.trim(),process.env.ADVERTISER_ACCESS_CODE?.trim()].includes(owner))throw new AppError('Owner code must differ from Teacher and Centre Manager codes.',503);
  if(d.role!=='advertiser'&&owner&&owner.length>=12&&equal(digest(code),digest(owner))){let rows=await db('school_users','GET',undefined,'identity=eq.__platform_owner__');if(!rows[0]){try{rows=await db('school_users','POST',{identity:'__platform_owner__',first_name:'Abduyx15870',last_name:'',role:'owner',center_id:'platform',book:'essential',unlocked_unit:1})}catch(e){rows=await db('school_users','GET',undefined,'identity=eq.__platform_owner__');if(!rows[0])throw e}}if(rows[0].teacher_code_hash)throw new AppError('Owner code has changed. Use your new code. / Owner kodi o‘zgartirilgan. Yangi kod bilan kiring.',403);return await signIn(req,rows[0])}
  const who=digest('teacher-code:'+(req.headers.get('x-nf-client-connection-ip')||req.headers.get('x-forwarded-for')?.split(',')[0]||'local'));if(!await db('rpc/school_login_guard','POST',{who}))throw new AppError('Too many incorrect attempts. Try again in 15 minutes.',429);
  if(d.role!=='advertiser'&&/^[A-Za-z0-9_-]{12}$/.test(code)){const hash=digest('teacher-personal:'+code),claims=await db('school_teacher_codes','GET',undefined,`id=eq.${hash}`);if(claims.length){const rows=await db('school_users','GET',undefined,`id=eq.${encodeURIComponent(claims[0].user_id)}`);const r=rows[0];if(!r||!['teacher','admin','administrator','owner','advertiser'].includes(r.role)||r.teacher_code_hash!==hash||r.disabled)throw new AppError('The access code is incorrect or no longer active. / Kirish kodi noto‘g‘ri yoki bekor qilingan.',403);if(!['owner','advertiser'].includes(r.role))await center(r.center_id||legacyCenter);return await signIn(req,r)}}
  let role='';const advertiser=process.env.ADVERTISER_ACCESS_CODE?.trim();if(advertiser&&[process.env.OWNER_ACCESS_CODE?.trim(),process.env.TEACHER_ACCESS_CODE?.trim(),process.env.ADMINISTRATOR_ACCESS_CODE?.trim()].includes(advertiser))throw new AppError('Use a distinct advertiser code.',503);const manager=process.env.ADMINISTRATOR_ACCESS_CODE?.trim(),teacher=process.env.TEACHER_ACCESS_CODE?.trim();if(advertiser&&advertiser.length===12&&equal(digest(code),digest(advertiser)))role='advertiser';else if(d.role!=='advertiser'&&manager&&manager.length>=12&&equal(digest(code),digest(manager)))role='administrator';else if(d.role!=='advertiser'&&teacher&&teacher.length>=12&&equal(digest(code),digest(teacher)))role='teacher';if(!role)throw new AppError('The access code is incorrect. / Kirish kodi noto‘g‘ri.',403);const c=role==='advertiser'?{id:'platform'}:await center(textValue(d.centerId,100));
  const selected=role==='advertiser'?'':String(d.subjectId||'english');if(role!=='advertiser'&&!(await subjects(c.id)).some(s=>s.id===selected&&s.enabled!==false))throw new AppError('Fanni tanlang.');const value=[Date.now()+600000,randomBytes(24).toString('hex')+'~'+selected,role,c.id].join('.');return Response.json({ok:true,role},{headers:{'Set-Cookie':`teacher_registration=${value}.${signature(value)}; HttpOnly; SameSite=Strict; Path=/api/auth; Max-Age=600${secure(req)}`,'Cache-Control':'no-store'}})
 }
 const first=textValue(d.firstName,60),last=textValue(d.lastName,60),password=textValue(d.password,128);if(password.length<8)throw new AppError('Use a password with at least 8 characters.');
 const name=(first+' '+last).normalize('NFKC').toLowerCase().replace(/\s+/g,' ').replace(/[‘’ʻʼ]/g,"'");
 if(!await db('rpc/school_login_guard','POST',{who:digest('login:'+name)}))throw new AppError('Too many attempts. Try again in 15 minutes.',429);
 if(d.action==='login'){
  const [old,indexed]=await Promise.all([db('school_users','GET',undefined,`identity=eq.${encodeURIComponent(name)}`),db('school_users','GET',undefined,`login_name=eq.${encodeURIComponent(name)}`)]);const candidates=[...new Map([...old,...indexed].map((r:any)=>[r.id,r])).values()].filter((r:any)=>r.role!=='owner'&&(!r.login_name||r.login_name===name)&&(d.role==='advertiser'?r.role==='advertiser':d.role==='teacher'?['teacher','administrator','advertiser'].includes(r.role):['student','admin','administrator'].includes(r.role))&&r.password_hash&&verifyPassword(password,r.password_hash));
  if(candidates.length!==1)throw new AppError(candidates.length?'More than one profile uses this name and password. Ask Owner to reset one password.':'The name or password is incorrect.',401);
  const r:any=candidates[0];if(r.disabled)throw new AppError('Your account is disabled.',403);if(r.role!=='advertiser')await center(r.center_id||legacyCenter);if(d.role==='teacher'&&!['teacher','administrator','advertiser'].includes(r.role))throw new AppError('This is not a teacher account.',403);return await signIn(req,r);
 }
 if(d.action==='registerAdvertiser'){
 const ticket=cookie(req,'teacher_registration'),[expires,nonce,role,centerId,sig]=ticket.split('.'),value=[expires,nonce,role,centerId].join('.');if(role!=='advertiser'||centerId!=='platform'||Number(expires)<=Date.now()||Number(expires)>Date.now()+600000||!nonce||!sig||!equal(signature(value),sig))throw new AppError('Enter the advertiser code first.',403);
 const identity='advertiser|'+name;const existing=await db('school_users','GET',undefined,`identity=eq.${encodeURIComponent(identity)}`);if(existing.length)throw new AppError('Reklamachi hisobi mavjud. Parolingiz bilan kiring.',409);
 const [r]=await db('school_users','POST',{identity,login_name:name,first_name:first,last_name:last,password_hash:hashPassword(password),role:'advertiser',center_id:'platform',book:'a1',unlocked_unit:1,settings:{language:'uz',style:'classic',layout:'cards',accent:'',audioRate:.7,voice:'Kore'}});return await signIn(req,r);
 }
 const c=await center(textValue(d.centerId,100));const scope=centerContext.getStore()!;scope.centerId=c.id;const identity=c.id===legacyCenter?name:c.id+'|'+name;
 let rows=await db('school_users','GET',undefined,`identity=eq.${encodeURIComponent(identity)}`),r=rows[0];
 if(d.action==='registerTeacher'){
  const ticket=req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith('teacher_registration='))?.slice(21)||'';const [expires,nonce,role,centerId,sig]=ticket.split('.');const value=[expires,nonce,role,centerId].join('.');if(centerId!==c.id||Number(expires)<=Date.now()||Number(expires)>Date.now()+600000||!nonce||!['teacher','administrator'].includes(role)||!sig||!equal(signature(value),sig))throw new AppError('Enter your centre registration code first.',403);
  if(!(await subjects(c.id)).some(s=>s.id===(nonce.split('~')[1]||'english')&&s.enabled!==false))throw new AppError('Tanlangan fan mavjud emas. Qaytadan fan tanlang.',403);
  if(['teacher','administrator'].includes(role)&&!/^[A-Za-z0-9_-]{12}$/.test(String(d.personalCode||'').trim()))throw new AppError('Choose your 12-character personal sign-in code. / 12 belgili shaxsiy kirish kodini tanlang.');
  if(['teacher','administrator'].includes(role))await checkTeacherCode(r?.id||digest(identity),d.personalCode);
  if(role==='administrator'){if(r&&(r.role!=='admin'||!verifyPassword(password,r.password_hash)))throw new AppError('This name is already registered.',409);const created=await createAdministrator({identity,login_name:name,first_name:first,last_name:last,password_hash:hashPassword(password),book:'essential',unlocked_unit:1},r?.password_hash||null);if(!created)throw new AppError('Centre Manager already exists. Sign in.',409);r=created}
  else if(r){if(r.role!=='teacher'||r.password_hash)throw new AppError('This name is already registered. Sign in.',409);r=await claimPendingTeacher(identity,hashPassword(password));if(!r)throw new AppError('Could not activate teacher.',409)}
  else [r]=await db('school_users','POST',{identity,login_name:name,first_name:first,last_name:last,password_hash:hashPassword(password),role,book:'essential',unlocked_unit:1,start_unit:1,start_lesson:1});
  if(['teacher','administrator'].includes(role)){const teacher_code_hash=await reserveTeacherCode(r.id,d.personalCode);await db('school_users','PATCH',{teacher_code_hash,subject_ids:[nonce.split('~')[1]||'english']},`id=eq.${encodeURIComponent(r.id)}`);r={...r,teacher_code_hash,subject_ids:[nonce.split('~')[1]||'english']};}
 }else if(d.action==='activateTeacher'){if(c.id!==legacyCenter)throw new AppError('Use your centre code.');r=await activateTeacher(identity,textValue(d.invite,128),hashPassword(password));if(!r)throw new AppError('Invitation is unavailable.',403)}
 else if(d.action==='register'){if(r)throw new AppError('This name is already registered. Sign in.',409);if(d.role!=='student')throw new AppError('Choose Student.',403);const subject=String(d.subjectId||'english');const chosen=(await subjects(c.id)).find(s=>s.id===subject&&s.enabled!==false) as any;if(!chosen||!chosen.code_hash)throw new AppError('Administrator bu fan kodini hali qo‘ymagan. O‘qituvchidan kod so‘rang.',403);if(chosen.code_hash!==courseCodeHash(c.id,subject,d.subjectCode))throw new AppError('Tanlangan markaz va fan kodi noto‘g‘ri.',403);const published=subject==='english'?[]:await db('school_materials','GET',undefined,'subject_id=eq.'+encodeURIComponent(subject));const maxUnit=Math.max(1,...published.filter((m:any)=>m.reviewed).map((m:any)=>m.units?.length||1)),courseStart=Number(d.courseStart)||1;if(!Number.isInteger(courseStart)||courseStart<1||subject!=='english'&&courseStart>maxUnit)throw new AppError('Mavjud UNITlardan birini tanlang.');const tracks=selectedTracks(d.tracks||{navigate:{book:'a1',unit:1,startLesson:1},essential:{book:'essential',unit:1,startLesson:1}});[r]=await db('school_users','POST',{identity,login_name:name,first_name:first,last_name:last,password_hash:hashPassword(password),role:'student',enrollments:[{centerId:c.id,subjectId:subject,startUnit:courseStart}],...trackFields(tracks)})}
 else if(!r||!r.password_hash||!verifyPassword(password,r.password_hash))throw new AppError('The centre, name or password is incorrect.',401);
 if(r.disabled)throw new AppError('Your account is disabled.',403);if(d.role==='teacher'&&!['teacher','administrator','advertiser'].includes(r.role))throw new AppError('This is not a teacher account.',403);return await signIn(req,r)
}catch(e){return fail(e)}})}
export async function DELETE(req:Request){return schoolScope(async()=>{try{mutation(req);const token=req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith('school_session='))?.split('=')[1];if(token)await db('school_sessions','DELETE',undefined,`token=eq.${digest(token)}`);return Response.json({ok:true},{headers:{'Set-Cookie':'school_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'}})}catch(e){return fail(e)}})}
