export const unavailable='Saytning umumiy Gemini xizmati hali ulanmagan. Sayt egasi serverga Gemini kalitini ulashi kerak. Oddiy mashqlar kalitsiz ishlaydi.';
export class GeminiError extends Error {constructor(message:string,public code:string,public providerStatus=0,public retryAfterSeconds?:number){super(message);this.name='GeminiError'}}
export function key(_provided?:unknown){const candidate=process.env.GEMINI_API_KEY?.trim().replace(/^(['"])(.*)\1$/,'$2');return typeof candidate==='string'&&/^[A-Za-z0-9._-]{20,512}$/.test(candidate)?candidate:undefined;}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');return !origin||new URL(origin).host===(req.headers.get('host')||new URL(req.url).host);}
export function modelName(provided?:unknown){const m=(typeof provided==='string'?provided:process.env.GEMINI_MODEL)?.trim().replace(/^models\//,'');return typeof m==='string'&&/^gemini-[a-zA-Z0-9.-]{1,80}$/.test(m)?m:'gemini-3.5-flash-lite';}
export function geminiFailure(status:number,data:any):GeminiError{
 const description=JSON.stringify(data?.error||{}).toLowerCase();
 if(/api.key.not.valid|api_key_invalid|api_key_service_blocked|api_key_http_referrer_blocked|api_key_ip_address_blocked|leaked|expired|invalid.*api.*key/.test(description)||status===401)return new GeminiError('Gemini API kaliti yaroqsiz, bloklangan yoki cheklangan. Netlifydagi GEMINI_API_KEY ni tekshiring.','AI_KEY',status);
 if(status===404||/model.*(not found|not supported|not available)/.test(description))return new GeminiError('Gemini modeli hisobingizda mavjud emas. GEMINI_MODEL sozlamasini tekshiring.','AI_MODEL',status);
 if(status===429){const details=Array.isArray(data?.error?.details)?data.error.details:[];const daily=details.some((d:any)=>(d.violations||[]).some((v:any)=>/perday|per_day|per.day/i.test(v.quotaId||v.quotaMetric||'')));const exhausted=details.some((d:any)=>(d.violations||[]).some((v:any)=>String(v.quotaValue)==='0'));const delay=details.find((d:any)=>String(d['@type']||'').endsWith('google.rpc.RetryInfo'))?.retryDelay;const seconds=typeof delay==='string'&&/^\d+(?:\.\d+)?s$/.test(delay)?Math.ceil(Number(delay.slice(0,-1))):0;const wait=!daily&&!exhausted&&seconds>0&&seconds<=120?seconds:undefined;return new GeminiError(daily?'Gemini kunlik limiti tugagan. Tayyor qismlar saqlandi. Limit tiklangach davom ettiring.':wait?`Gemini vaqtinchalik so‘rov limitiga yetdi. ${wait} soniyadan keyin qayta uriniladi.`:'Gemini kvotasi tugagan. AI Studio kvotasini tekshiring yoki keyinroq urinib ko‘ring.','AI_QUOTA',status,wait)}
 if(status===402||/billing|prepay|paid tier|free tier.*not available/.test(description))return new GeminiError('Gemini hisobida to‘lov yoki xizmat hududi bo‘yicha cheklov bor. AI Studio hisobini tekshiring.','AI_ACCOUNT',status);
 if(status===403)return new GeminiError('Gemini xizmatiga ruxsat berilmagan. API kalitining loyiha va API cheklovlarini tekshiring.','AI_PERMISSION',status);
 if(status===400)return new GeminiError('Gemini so‘rov parametrini qabul qilmadi. Sayt egasi model sozlamasi va server jurnalini tekshirishi kerak.','AI_REQUEST',status);
 return new GeminiError('Gemini xizmati vaqtincha javob bermadi. Qayta urinib ko‘ring.','AI_UNAVAILABLE',status);
}
async function responseData(r:Response){try{return await r.json()}catch{throw new GeminiError('Gemini serveridan to‘liq javob kelmadi. Qayta urinib ko‘ring.','AI_RESPONSE',r.status)}}
const workingModels=new Map<string,{model:string;expires:number}>();
type Options={apiKey:string;model?:string;instructions:string;parts:any[];schema?:object;maxTokens?:number;fast?:boolean;timeoutMs?:number};
export async function gemini(options:Options):Promise<string>{
 const {apiKey,instructions,parts,schema,maxTokens=4000}=options;const requested=modelName(options.model),choiceKey=apiKey+'|'+requested,saved=workingModels.get(choiceKey);let model=saved&&saved.expires>Date.now()?saved.model:requested,retried=false;const tried=new Set<string>();let budget=maxTokens,emptyRetried=false;const deadline=Date.now()+(options.timeoutMs||35000);
 for(let attempt=0;attempt<3;attempt++){
  tried.add(model);let res:Response;const remaining=deadline-Date.now();if(remaining<=0)throw new GeminiError('Gemini javobini kutish vaqti tugadi. Qayta urinib ko‘ring.','AI_TIMEOUT');const thinking=options.fast?(model.startsWith('gemini-2.5-flash')?{thinkingBudget:0}:/^gemini-3[.-].*flash/.test(model)?{thinkingLevel:/^gemini-3\.[78]-flash/.test(model)?'low':'minimal'}:undefined):undefined;
  try{res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:'POST',headers:{'x-goog-api-key':apiKey,'Content-Type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:instructions}]},contents:[{role:'user',parts}],generationConfig:{maxOutputTokens:budget,...(thinking?{thinkingConfig:thinking}:{}),temperature:model.startsWith('gemini-3')?1:.2,...(schema?{responseMimeType:'application/json',responseJsonSchema:schema}:{})}}),signal:AbortSignal.timeout(Math.min(options.fast?remaining:25000,remaining))})}catch{throw new GeminiError('Gemini bilan aloqa yoki kutish vaqti tugadi. Qayta urinib ko‘ring.','AI_TIMEOUT')}
  const data:any=await responseData(res);
  if(!res.ok){const error=geminiFailure(res.status,data);
   if(error.code==='AI_MODEL'){workingModels.delete(choiceKey);let list:Response;try{list=await fetch('https://generativelanguage.googleapis.com/v1beta/models',{headers:{'x-goog-api-key':apiKey},signal:AbortSignal.timeout(7000)})}catch{throw error}if(list.ok){const available=await responseData(list);const candidates=(available.models||[]).filter((m:any)=>m.supportedGenerationMethods?.includes('generateContent')&&/flash/.test(m.name)&&!/(tts|image|live|audio|embedding)/.test(m.name)&&!tried.has(m.name.replace(/^models\//,'')));candidates.sort((a:any,b:any)=>Number(!/flash-lite/.test(a.name))-Number(!/flash-lite/.test(b.name)));if(candidates[0]){model=candidates[0].name.replace(/^models\//,'');continue}}throw error}
   if([408,500,502,503,504].includes(res.status)&&!retried){retried=true;await new Promise(resolve=>setTimeout(resolve,400));continue}throw error;
  }
  const text=(data.candidates?.[0]?.content?.parts||[]).filter((p:any)=>typeof p.text==='string'&&!p.thought).map((p:any)=>p.text).join('\n');
  const reason=data.candidates?.[0]?.finishReason;if(data.promptFeedback?.blockReason||['SAFETY','RECITATION','PROHIBITED_CONTENT','BLOCKLIST'].includes(reason))throw new GeminiError('Gemini bu sahifa yoki matnga javobni chekladi. Boshqa sahifa yoki matn bilan urinib ko‘ring.','AI_BLOCKED');if(reason==='MAX_TOKENS'||!text){if(!emptyRetried&&attempt<2){emptyRetried=true;budget=Math.min(16000,Math.max(1024,budget*2));continue}throw new GeminiError(reason==='MAX_TOKENS'?'Gemini javobi to‘liq tugamadi. Matnni kichikroq qismlarga ajratib urinib ko‘ring.':'Gemini bu so‘rovga matn qaytarmadi. Boshqa sahifa yoki matn bilan urinib ko‘ring.',reason==='MAX_TOKENS'?'AI_TRUNCATED':'AI_EMPTY');}if(model!==requested){if(workingModels.size>=32)workingModels.delete(workingModels.keys().next().value!);workingModels.set(choiceKey,{model,expires:Date.now()+600000})}return text;
 }
 throw new GeminiError('Gemini hisobida ishlaydigan model topilmadi. GEMINI_MODEL ni tekshiring.','AI_MODEL');
}
