// Shared by the browser and server: accepting a spelling difference must never
// make the client disagree with the saved grade.
export type AnswerRules={answer:string;accepted?:string[];caseSensitiveWords?:string[]};
const places=new Set(('London Paris Tashkent Toshkent Uzbekistan England Britain America Canada Australia Italy France Germany Spain China Japan Russia Moscow Berlin Madrid Rome Tokyo Oxford Cambridge New York Sydney Manchester Liverpool USA UK UAE United Kingdom Los Angeles Washington Beijing Bangkok Seoul Monday Tuesday Wednesday Thursday Friday Saturday Sunday Samarkand Samarqand Bukhara Buxoro Africa Europe Asia India Turkey Istanbul').split(' '));
const ordinary=new Set(('The A An I This That These Those My Your His Her Our Their It He She We They There Here What Where When Why Who How Do Does Did Is Are Was Were Have Has Had Can Could Will Would Should Please Let Yes No Hello Hi Good Listen Read Write Choose Complete Put Build Today Yesterday Tomorrow After Before In On At To From With For And But Because If Every Some All Many').split(' ').map(v=>v.toLowerCase()));
export function tokens(s:string){return s.normalize('NFKC').replace(/[‘’ʻʼ`]/g,"'").match(/[\p{L}\p{N}]+(?:'[\p{L}]+)*/gu)||[]}
export function answerNormal(s:string){return s.normalize('NFKC').replace(/[‘’ʻʼ`]/g,"'").toLowerCase().replace(/\bi'm\b/g,'i am').replace(/\b(can't|cannot)\b/g,'can not').replace(/\bwon't\b/g,'will not').replace(/\b([\p{L}]+)n't\b/gu,'$1 not').replace(/\b([\p{L}]+)'re\b/gu,'$1 are').replace(/\b([\p{L}]+)'ve\b/gu,'$1 have').replace(/\b([\p{L}]+)'ll\b/gu,'$1 will').replace(/[^\p{L}\p{N}'\s]/gu,' ').replace(/\s+/g,' ').trim()}
export function properCase(expected:string,actual:string,explicit:string[]=[]){const e=tokens(expected),a=tokens(actual);const required=e.filter((v,i)=>explicit.includes(v)||places.has(v)||(/^[A-Z][a-z]/.test(v)&&!ordinary.has(v.toLowerCase())&&i>0));for(const word of required){const matches=a.filter(v=>v.toLowerCase()===word.toLowerCase());if(!matches.length||matches.some(v=>v!==word))return false}return true}
export function answerMatches(q:AnswerRules,a:string,punctuation=false){return [q.answer,...q.accepted||[]].some(expected=>{const equal=punctuation?expected.normalize('NFKC').replace(/[‘’]/g,"'").trim().replace(/\s+/g,' ').toLowerCase()===a.normalize('NFKC').replace(/[‘’]/g,"'").trim().replace(/\s+/g,' ').toLowerCase():answerNormal(expected)===answerNormal(a);return equal&&properCase(expected,a,q.caseSensitiveWords)})}
