'use client';
import {courseFetch} from './course-client';
import {bookStep} from './book-retry';
import {segments} from './courses';
export function originalBook(file:File){if(file.size>100*1024*1024)throw new Error('100 MBgacha fayl yuklang.');const mime=/\.pdf$/i.test(file.name)?'application/pdf':/\.docx$/i.test(file.name)?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':/\.txt$/i.test(file.name)?'text/plain':'';if(!mime)throw new Error('PDF, DOCX yoki TXT fayl tanlang.');const chunkBytes=135000;return{mime,originalParts:Math.ceil(file.size/chunkBytes),async originalChunk(index:number){const binary=new Uint8Array(await file.slice(index*chunkBytes,(index+1)*chunkBytes).arrayBuffer());let raw='';for(let i=0;i<binary.length;i+=8192)raw+=String.fromCharCode(...binary.subarray(i,i+8192));return btoa(raw)}}}
export async function extractBook(file:File,center:string,subject:string,onProgress:(text:string)=>void,options:{id?:string;cancelled?:()=>boolean}={}){
 if(file.size>100*1024*1024)throw new Error('100 MBgacha fayl yuklang.');const bytes=await file.arrayBuffer();let text='',mime=file.type;
 if(/\.txt$/i.test(file.name)){mime='text/plain';text=new TextDecoder().decode(bytes)}
 else if(/\.docx$/i.test(file.name)){mime='application/vnd.openxmlformats-officedocument.wordprocessingml.document';const mammoth=await import('mammoth/mammoth.browser');text=(await mammoth.extractRawText({arrayBuffer:bytes})).value}
 else if(/\.pdf$/i.test(file.name)){mime='application/pdf';const pdf=await import('pdfjs-dist');pdf.GlobalWorkerOptions.workerSrc='/pdf.worker.min.mjs';const task=pdf.getDocument({data:new Uint8Array(bytes)});const doc=await task.promise;try{if(doc.numPages>1000)throw new Error('Bir faylda 1000 sahifagacha yuklang.');for(let i=1;i<=doc.numPages;i++){if(options.cancelled?.())throw new Error('Tayyorlash to‘xtatildi. Fayl va o‘qilgan OCR sahifalar saqlandi.');onProgress(`Sahifa o‘qilmoqda: ${i}/${doc.numPages}`);const page=await doc.getPage(i);const content=await page.getTextContent();let pageText=content.items.map((x:any)=>x.str+(x.hasEOL?'\n':' ')).join('');if(!pageText.trim()){if(typeof page.getOperatorList==='function'){const ops=await page.getOperatorList();const images=[pdf.OPS.paintImageXObject,pdf.OPS.paintInlineImageXObject,pdf.OPS.paintImageMaskXObject,pdf.OPS.paintImageXObjectRepeat];if(!ops.fnArray.some((code:number)=>images.includes(code))){page.cleanup();continue}}const base=page.getViewport({scale:1});const viewport=page.getViewport({scale:Math.min(2,1600/base.width)});const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvas,canvasContext:canvas.getContext('2d')!,viewport}).promise;try{let image=canvas.toDataURL('image/jpeg',.8);for(const quality of [.65,.5,.35]){if(image.length<=1450000)break;image=canvas.toDataURL('image/jpeg',quality)}if(image.length>1450000)throw new Error('Sahifa tasviri juda katta. PDFni kichikroq sahifalarga ajrating.');pageText=(await bookStep(()=>courseFetch(center,subject,{action:'ocr',id:options.id,page:i,image}),onProgress,options.cancelled)).text}catch(e){throw new Error(`PDF ${i}-sahifasini o‘qish (OCR): ${(e as Error).message}`)}finally{canvas.width=canvas.height=0;}}if(pageText.trim()==='[NO_TEXT]'){page.cleanup?.();continue}text+=pageText+'\n\n';page.cleanup?.();if(text.length>900000)throw new Error('Matn juda uzun. Kitobni qismlarga ajrating.');}}finally{await task.destroy()}}
 else throw new Error('PDF, DOCX yoki TXT fayl tanlang.');
 if(text.trim().length<10)throw new Error('Fayldan o‘qiladigan matn topilmadi. Matnli PDF yoki TXT yuklang.');if(text.length>900000)throw new Error('Matn juda uzun. Kitobni qismlarga ajrating.');
 return{parts:segments(text,1000),text,...originalBook(file)};
}
