import 'server-only';
import {AppError,db,digest,textValue} from './school-server';
import {centerContext} from './center-context';
import {englishSubject,enrollments,type Subject} from './courses';
import type {User} from './school-types';
export const q=(id:string)=>`id=eq.${encodeURIComponent(id)}`;
export async function subjects(center:string):Promise<Subject[]>{const rows=await db('school_subjects','GET',undefined,`center_id=eq.${encodeURIComponent(center)}`);return[rows.find((r:any)=>r.english||r.subject_key==='english')||{...englishSubject(center),id:digest(center+'|english'),subject_key:'english'},...rows.filter((r:any)=>r.subject_key!=='english'&&!r.english)].map((r:any)=>({...r,id:r.subject_key||r.id,codeSet:!!r.code_hash}));}
export function courseCode(value:unknown){const code=textValue(value,4).toUpperCase();if(!/^[A-Z0-9]{4}$/.test(code))throw new AppError('Fan kodi 4 ta harf yoki sondan iborat bo‘lsin.');return code}
export function courseCodeHash(center:string,subject:string,value:unknown){return digest('subject|'+center+'|'+subject+'|'+courseCode(value))}
export async function selectCourse(u:User,center:string,subject:string){const scope=centerContext.getStore()!;if(!scope.demo&&u.role!=='owner'&&center!==u.centerId&&!enrollments(u).some(e=>e.centerId===center&&e.subjectId===subject))throw new AppError('Bu markazga ruxsat yo‘q.',403);if(!scope.demo&&u.role==='student'&&!enrollments(u).some(e=>e.centerId===center&&e.subjectId===subject))throw new AppError('Bu fanga ruxsat yo‘q. Ownerga yozing.',403);if(!scope.demo&&u.role==='teacher'&&!(u.subjectIds||['english']).includes(subject))throw new AppError('Bu fan sizga biriktirilmagan.',403);scope.centerId=center;scope.subjectId=subject;if(u.role==='student'&&Array.isArray(u.enrollments)){const e=u.enrollments.find(e=>e.centerId===center&&e.subjectId===subject) as any;u.groupId=e?.groupId||(e===u.enrollments[0]?u.groupId:null)}const s=(await subjects(center)).find(s=>s.id===subject&&s.enabled!==false);if(!s)throw new AppError('Fan topilmadi.',404);return s}
export async function groupsFor(u:User){const groups=await db('school_groups');return u.role==='teacher'?groups.filter((g:any)=>g.teacher_id===u.id):u.role==='admin'?groups.filter((g:any)=>g.id===u.groupId):groups}
export async function materialFor(u:User,id:string,subject:string){const rows=await db('school_materials','GET',undefined,q(id)),m=rows[0];if(!m||m.subject_id!==subject)throw new AppError('Kitob topilmadi.',404);if(u.role==='owner'||u.role==='administrator'||m.user_id===u.id)return m;if(u.role==='teacher'){const gs=await groupsFor(u),users=await db('school_users');if(users.some((r:any)=>r.id===m.user_id&&gs.some((g:any)=>g.id===r.group_id))||m.shared_groups?.some((id:string)=>gs.some((g:any)=>g.id===id)))return m}if(m.reviewed&&(m.shared_groups||[]).includes(u.groupId))return m;throw new AppError('Kitobga ruxsat yo‘q.',403)}
export function canPublish(u:User){return u.role==='teacher'||u.role==='owner'}
export async function courseOwnerNotice(u:User,title:string,body:string){const scope=centerContext.getStore()!;if(scope.demo)return;const previous=scope.centerId,owner=scope.owner;try{scope.centerId=null;scope.owner=true;const users=await db('school_users');const {notify}=await import('./notifications-server');for(const r of users.filter((r:any)=>r.role==='owner'&&!r.disabled))await notify(r.id,title,body,'course',u.id)}finally{scope.centerId=previous;scope.owner=owner}}
