import {GeminiError} from './ai';
import {demoDb,demoUser,persistentDemoDb} from './demo-server';
import {tracksFromRow,trackAllowed} from './study-tracks';
import {centerContext,legacyCenter} from './center-context';
import {paymentState,tashkentDate} from './billing';
import 'server-only';
import {createHash,randomBytes,scryptSync,timingSafeEqual} from 'node:crypto';
import type {User} from './school-types';
export class AppError extends Error {constructor(message:string,public status=400){super(message)}}
// Shared server-only Firestore adapter; browser access is denied by rules.
// @ts-ignore JavaScript adapter shared with setup scripts and scheduled jobs.
import {claimExamWindow as firebaseExamWindow,createOwnerSession as firebaseOwnerSession,moveSchoolUserCenter as firebaseMoveUser,db as firebaseDb,activateTeacher as firebaseActivateTeacher,claimPendingTeacher as firebaseClaimPendingTeacher,createAdministrator as firebaseCreateAdministrator,resignTemporaryAdministrator as firebaseResignTemporaryAdministrator} from '../scripts/firebase-store.mjs';
async function rawDb(table:string,method='GET',data?:unknown,query=''){
 const scope=centerContext.getStore();const cache=scope?(scope.rawReads??=new Map<string,Promise<any>>()):null;const key=table+'|'+query;
 if(method!=='GET'&&cache)for(const k of cache.keys())if(k.startsWith(table+'|'))cache.delete(k);
 try{if(method==='GET'&&cache){let pending=cache.get(key);if(!pending){pending=Promise.resolve(firebaseDb(table,method,data,query));cache.set(key,pending);pending.catch(()=>cache.delete(key))}return structuredClone(await pending)}return await firebaseDb(table,method,data,query)}catch(e:any){if(e.status===409)throw new AppError('This record already exists.',409);console.error('Firebase request failed',table,e.status||'configuration');const status=Number(e.status);const hint=status===429?'Firebase so‘rov limiti tugadi (HTTP 429). Tayyor qismlar saqlangan. Firebase kvotasini tekshiring va keyin davom ettiring.':status===401||status===403?'Firebase server access was denied. Check the server service-account configuration. / Firebase server ruxsati rad etildi.':status===404?'Firebase database was not found. Check the project and database settings. / Firebase bazasi topilmadi.':status>=500?'Firebase is temporarily unavailable. Please try again. / Firebase vaqtincha ishlamayapti, qayta urinib ko‘ring.':status===400?'Firebase rejected the database request. Please share the server error code. / Firebase so‘rovni rad etdi.':'Firebase server configuration or connection failed. Check the terminal. / Firebase ulanishi yoki server sozlamasi xato. Terminalni tekshiring.';throw new AppError(hint+(Number.isFinite(status)?' (HTTP '+status+')':''),503)}
}
export async function db(table:string,method='GET',data?:any,query=''):Promise<any[]|any>{
 const scope=centerContext.getStore();
 const subjectTables=['school_groups','school_assignments','school_events','school_questions','school_notes'];if(scope?.subjectId&&!(scope.owner&&!scope.centerId)&&subjectTables.includes(table)){if(method==='POST')data={...data,subject_id:data?.subject_id||scope.subjectId};if(method==='GET')return (await scopedDb()).filter((r:any)=>(r.subject_id||'english')===scope.subjectId||table==='school_events'&&(r.allGroups||r.broadcast_id));}
 return scopedDb();async function scopedDb(){
 if(scope?.demoKey)return persistentDemoDb(scope.demoKey,table,method,data,query,rawDb,scope.centerId||'demo');
 if(table==='rpc/school_student_stats'&&scope){const attempts=await db('school_attempts');const stats=new Map<string,any>();for(const a of attempts){const v=stats.get(a.user_id)||{user_id:a.user_id,lessons:new Set(),seconds:0};v.seconds+=a.seconds||0;if(a.completed)v.lessons.add([a.book,a.unit,a.lesson].join('|'));stats.set(a.user_id,v)}return [...stats.values()].map(v=>({...v,lessons:v.lessons.size}))}
 if(method==='GET'&&table==='school_teacher_codes')return rawDb(table,method,data,query);
 if(!scope?.centerId&&!scope?.owner||['school_sessions','school_centers','school_lesson_content','rpc/school_login_guard'].includes(table))return rawDb(table,method,data,query);
 const matches=(r:any)=>scope.owner&&(!scope.centerId||r.role==='owner')||(r.center_id||legacyCenter)===scope.centerId||table==='school_users'&&r.enrollments?.some((e:any)=>e.centerId===scope.centerId&&e.subjectId===scope.subjectId);
 if(method==='POST'){const center=data?.center_id||scope.centerId||(scope.owner?legacyCenter:null);if(!scope.owner&&center!==scope.centerId)throw new AppError('Other learning centre access denied.',403);if(scope.owner&&!scope.centerId&&!data?.center_id&&['school_groups','school_assignments','school_events','school_users'].includes(table))throw new AppError('Choose a learning centre first.');return rawDb(table,method,{...data,center_id:center},query)}
 const params=new URLSearchParams(query),limit=Number(params.get('limit'));params.delete('limit');const raw=await rawDb(table,'GET',undefined,params.toString());let allowed=raw.filter(matches);if(scope.effectiveRole==='teacher'&&table==='school_groups')allowed=allowed.filter((r:any)=>r.teacher_id===scope.effectiveUserId);if(scope.effectiveRole==='admin'){const groups=scope.groupIds||[];if(table==='school_groups')allowed=allowed.filter((r:any)=>groups.includes(r.id));else if(['school_events','school_assignments'].includes(table))allowed=allowed.filter((r:any)=>method==='GET'?(table==='school_events'&&r.allGroups)||r.groups?.some((g:string)=>groups.includes(g)):!r.allGroups&&!r.broadcast_id&&r.groups?.length&&r.groups.every((g:string)=>groups.includes(g)));else if(table==='school_users')allowed=allowed.filter((r:any)=>r.id===scope.effectiveUserId||['student','admin'].includes(r.role)&&groups.includes(r.group_id));else if(table==='school_questions')allowed=allowed.filter((r:any)=>groups.includes(r.group_id));else if(['school_attempts','school_progress','school_notes'].includes(table)){const members=await rawDb('school_users');const ids=new Set(members.filter((r:any)=>matches(r)&&groups.includes(r.group_id)).map((r:any)=>r.id));allowed=allowed.filter((r:any)=>ids.has(r.user_id))}}
 if(method==='GET'){if(table==='school_users'&&scope.subjectId){if(!scope.owner)allowed=allowed.filter((r:any)=>!['student','admin'].includes(r.role)||!Array.isArray(r.enrollments)&&scope.subjectId==='english'||r.enrollments?.some((e:any)=>e.subjectId===scope.subjectId&&e.centerId===scope.centerId));allowed=allowed.map((r:any)=>{const e=r.enrollments?.find((e:any)=>e.subjectId===scope.subjectId&&e.centerId===scope.centerId);return e?{...r,center_id:scope.centerId,group_id:e.groupId||(r.enrollments?.[0]===e?r.group_id:null)}:r})}return limit>0?allowed.slice(0,limit):allowed;}
 if(data?.center_id&&!scope.owner&&data.center_id!==scope.centerId)throw new AppError('Centre cannot be changed.',403);
 if(raw.length&&!allowed.length)throw new AppError('Other learning centre access denied.',403);
 const result=[];for(const r of allowed){if(!r.id)throw new AppError('Record cannot be changed.');result.push(...await rawDb(table,method,data,`id=eq.${encodeURIComponent(r.id)}`))}return result;
}
}
export function hashPassword(p:string){const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(p,salt,64).toString('hex')}
export function verifyPassword(p:string,h:string){try{const [s,v]=h.split(':');const a=Buffer.from(v,'hex'),b=scryptSync(p,s,64);return a.length===b.length&&timingSafeEqual(a,b)}catch{return false}}
export function digest(s:string){return createHash('sha256').update(s).digest('hex')}
export function safeUser(r:any):User{return {enrollments:r.enrollments,subjectIds:r.subject_ids,id:r.id,firstName:r.role==='owner'&&(!r.first_name||r.first_name==='Owner')?'Abduyx15870':r.first_name,lastName:r.last_name,role:r.role,centerId:r.center_id||legacyCenter,groupId:r.group_id,book:r.book,unlockedUnit:r.unlocked_unit,startUnit:r.start_unit||1,startLesson:r.start_lesson||1,createdAt:r.created_at,disabled:!!r.disabled,temporaryAdministrator:!!r.temporary_administrator,payment:paymentState(r.billing),settings:r.settings,courses:tracksFromRow(r)}}
export async function current(req:Request,allowBlocked=false){
 const token=req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith('school_session='))?.split('=')[1];if(!token)throw new AppError('Please sign in.',401);
 const sessions=await rawDb('school_sessions','GET',undefined,`id=eq.${digest(token)}`);if(!sessions[0]||sessions[0].token!==digest(token)||Date.parse(sessions[0].expires_at)<=Date.now()||!Number.isFinite(Date.parse(sessions[0].expires_at)))throw new AppError('Your session has expired. Please sign in again.',401);
 const rows=await rawDb('school_users','GET',undefined,`id=eq.${sessions[0].user_id}`);if(!rows[0])throw new AppError('Please sign in.',401);let row=rows[0];if(row.disabled)throw new AppError('Your account has been disabled by the Administrator.',403);
 const scope=centerContext.getStore();const actor={id:row.id,role:row.role};if(scope)scope.actor=actor;
 const target=req.headers.get('x-owner-user'),demoRole=req.headers.get('x-demo-role');
 if(target){if(row.role!=='owner'||demoRole)throw new AppError('Owner account access required.',403);const targets=await rawDb('school_users','GET',undefined,`id=eq.${encodeURIComponent(target)}`);if(!targets[0]||!['student','teacher','administrator','admin'].includes(targets[0].role))throw new AppError('Choose an available account.');row=targets[0]}
 if(demoRole){if(!['owner','advertiser'].includes(actor.role)||!['advertiser','student','teacher','administrator','admin'].includes(demoRole))throw new AppError('Demo access denied.',403);{const key=req.headers.get('x-demo-key');if(!key||!/^[-a-zA-Z0-9]{16,100}$/.test(key))throw new AppError('Reopen the demonstration.');if(scope){scope.demo=true;scope.demoKey=digest(token+'|'+key);scope.centerId=req.headers.get('x-learning-center')||'demo';scope.owner=false;}row=(await persistentDemoDb(scope!.demoKey!,'school_users','GET',undefined,`id=eq.${demoUser(demoRole)}`,rawDb,scope!.centerId||'demo'))[0];if(actor.role==='owner'&&demoRole!=='advertiser')row={...row,first_name:'Anonim',last_name:''}}}
 const pickedSubject=req.headers.get('x-subject-id')||row.subject_ids?.[0]||row.enrollments?.[0]?.subjectId||'english',pickedCenter=req.headers.get('x-learning-center');if(!scope?.demo&&row.role==='student'&&(!Array.isArray(row.enrollments)?pickedSubject!=='english'||!!pickedCenter&&pickedCenter!==(row.center_id||legacyCenter):!row.enrollments.some((e:any)=>e.subjectId===pickedSubject&&e.centerId===(pickedCenter||row.center_id))))throw new AppError('Bu fanga ruxsat yo‘q.',403);if(!scope?.demo&&row.role==='teacher'&&!(row.subject_ids||['english']).includes(pickedSubject))throw new AppError('Bu fan sizga biriktirilmagan.',403);if(scope)scope.subjectId=pickedSubject;if(row.role==='student'&&Array.isArray(row.enrollments)){const e=row.enrollments.find((e:any)=>e.subjectId===pickedSubject&&e.centerId===(pickedCenter||row.center_id));if(e)row={...row,center_id:e.centerId,group_id:e.groupId||(e===row.enrollments[0]?row.group_id:null)}}
 if(scope){scope.owner=row.role==='owner';scope.effectiveRole=row.role;scope.effectiveUserId=row.id;if(!scope.demo)scope.centerId=scope.owner?(req.headers.get('x-center-id')||null):(row.center_id||legacyCenter);if(row.role==='admin')scope.groupIds=row.group_id?[row.group_id]:[];
  if(row.role==='student'&&['/api/audio','/api/media'].includes(new URL(req.url).pathname)&&Array.isArray(row.enrollments)&&!row.enrollments.some((e:any)=>e.subjectId==='english'))throw new AppError('English ruxsati kerak.',403);if(scope.centerId&&!['platform','demo'].includes(scope.centerId)){const centers=await rawDb('school_centers','GET',undefined,`id=eq.${encodeURIComponent(scope.centerId)}`);if(scope.centerId!==legacyCenter&&(!centers[0]||centers[0].disabled))throw new AppError('Learning centre is unavailable.',403)}
 }
 if(!row.billing){row={...row,billing:{status:'paid',paidAt:tashkentDate()}};if(!demoRole||scope?.demo)await db('school_users','PATCH',{billing:row.billing},`id=eq.${row.id}`)}
 const user=safeUser(row);if(!allowBlocked&&user.role==='student'&&user.payment.blocked&&actor.role!=='owner')throw new AppError('Oylik to‘lovni tezroq to‘lang. Administrator to‘langan deb belgilagach darslar ochiladi.',402);return user
}
export function mutation(req:Request){const origin=req.headers.get('origin');if(origin&&new URL(origin).host!==(req.headers.get('host')||new URL(req.url).host))throw new AppError('Request denied.',403)}
export function teacher(u:User){if(!['teacher','owner'].includes(u.role))throw new AppError('Only the teacher can change this.',403)}
export function staff(u:User){if(!['teacher','admin','administrator','owner'].includes(u.role))throw new AppError('Teacher access required.',403)}
export function textValue(v:unknown,max=4000){if(typeof v!=='string'||!v.trim()||v.length>max)throw new AppError('Please check the entered text.');return v.trim()}
export function fail(e:unknown){if(e instanceof GeminiError)return Response.json({error:e.message,code:e.code,providerStatus:e.providerStatus,...(e.retryAfterSeconds?{retryAfterSeconds:e.retryAfterSeconds}:{})},{status:503,headers:{'Cache-Control':'no-store'}});if(e instanceof Error&&!(e instanceof AppError)&&/^Firebase (server|database|project|service account)/.test(e.message))return Response.json({error:'Firebase bazasi bilan ulanish xatosi. Serverdagi Firebase sozlamalari va Firestore ruxsatlarini tekshiring.',code:'DATABASE_CONNECTION'},{status:503,headers:{'Cache-Control':'no-store'}});return Response.json({error:e instanceof AppError?e.message:'Something went wrong. Please try again.'},{status:e instanceof AppError?e.status:500,headers:{'Cache-Control':'no-store'}})}
export function permitted(u:User,book:string,unit:number){return u.role!=='student'||((!Array.isArray(u.enrollments)||u.enrollments.some(e=>e.subjectId==='english'))&&trackAllowed(u,book,unit))}

export async function activateTeacher(identity:string,invite:string,passwordHash:string){try{return await firebaseActivateTeacher(identity,invite,passwordHash)}catch{throw new AppError('Could not activate the teacher account. Please try again.',503)}}

export async function claimPendingTeacher(identity:string,passwordHash:string){try{return await firebaseClaimPendingTeacher(identity,passwordHash)}catch{throw new AppError("Could not create teacher account. Try again.",503)}}

export function administrator(u:User){if(!['administrator','owner'].includes(u.role))throw new AppError('Only the Administrator can change this.',403)}

export async function createAdministrator(data:any,expectedHash:string|null=null){try{return await firebaseCreateAdministrator({...data,center_id:centerContext.getStore()?.centerId||legacyCenter},expectedHash)}catch{throw new AppError("Could not create Administrator account. Try again.",503)}}

export async function resignTemporaryAdministrator(userId:string){if(centerContext.getStore()?.demoKey)return false;try{return await firebaseResignTemporaryAdministrator(userId,centerContext.getStore()?.centerId||legacyCenter)}catch{throw new AppError("Could not leave Administrator role. Try again.",503)}}

export async function moveUserCenter(userId:string,centerId:string){try{return await firebaseMoveUser(userId,centerId)}catch(e:any){console.error('Atomic centre move failed');throw new AppError(e?.message?.includes('too many records')?'This account is too large to move in one operation. No data was changed.':e?.message?.includes('already has a Centre Manager')?'That centre already has a Centre Manager.':'Could not move this account. No data was changed; please retry.',409)}}

export async function ownerSession(data:{token:string;user_id:string;expires_at:string},deviceId:string,currentToken=''){try{return await firebaseOwnerSession(data,deviceId,currentToken)}catch(e:any){if(e.code==='OWNER_DEVICE_LIMIT')throw new AppError('Owner device limit reached (3 devices). Sign out on one device first. / Owner uchun 3 ta qurilma limiti to‘lgan. Avval bittasidan hisobdan chiqing.',409);console.error('Owner session update failed',e.status||'operation');throw new AppError('Could not update Owner devices. Please try again. / Owner qurilmalarini tekshirishda server xatosi. Qayta urinib ko‘ring.',503)}}

export async function claimExamWindow(data:any){
 const scope=centerContext.getStore();
 let result:any;
 if(scope?.demoKey){
  const id=digest(data.user_id+'|'+data.exam),old=(await db('school_exam_windows','GET',undefined,'id=eq.'+id))[0];
  if(old?.session_id===data.session_id)result=old.suite_id===data.suite_id&&old.center_id===data.center_id?old:{conflict:true};
  else if(old&&Date.parse(old.next_at)>Date.now())result={blocked:true,next_at:old.next_at};
  else{result={...data,id,started_at:new Date().toISOString(),next_at:new Date(Date.now()+14*86400000).toISOString()};await db('school_exam_windows',old?'PATCH':'POST',result,old?'id=eq.'+id:'');}
 }else try{result=await firebaseExamWindow(data)}catch{throw new AppError('Testni boshlash saqlanmadi. Qayta urinib ko‘ring.',503)}
 if(result.blocked)throw new AppError('To‘liq testni 14 kunda bir marta topshirish mumkin. Keyingi sana: '+new Date(result.next_at).toLocaleString('uz-UZ',{timeZone:'Asia/Tashkent'})+' (Toshkent)',429);
 if(result.conflict)throw new AppError('Bu sessiya boshqa test yoki markazga tegishli.',409);
 return result;
}
