// Continuous voice conversation. Only starts after an explicit user gesture.
export type VoicePhase='idle'|'listening'|'thinking'|'speaking';
export class VoiceSession {
 private stream:MediaStream|null=null;private context:AudioContext|null=null;private analyser:AnalyserNode|null=null;private recognition:any=null;private frame=0;private timer:ReturnType<typeof setTimeout>|undefined;private retry:ReturnType<typeof setTimeout>|undefined;private active=false;private epoch=0;private loudAt=0;private baseline=.008;private speakingAt=0;phase:VoicePhase='idle';
 constructor(private hooks:{utterance:(text:string)=>void;interrupt:()=>void;phase:(v:VoicePhase)=>void;error:(text:string)=>void}){}
 async start(){const R=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!R)throw new Error('Ovozli suhbat uchun Chrome yoki Edge ishlating.');if(!navigator.mediaDevices?.getUserMedia)throw new Error('Mikrofon uchun HTTPS yoki localhost kerak.');const epoch=++this.epoch;this.active=true;try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(!this.active||epoch!==this.epoch){stream.getTracks().forEach(t=>t.stop());return false}this.stream=stream;const C=window.AudioContext||(window as any).webkitAudioContext;this.context=new C();await this.context!.resume();if(!this.active||epoch!==this.epoch){this.stop();return false}this.analyser=this.context!.createAnalyser();this.analyser.fftSize=1024;this.context!.createMediaStreamSource(stream).connect(this.analyser);this.monitor();return true}catch(e){this.stop();throw e}}
 private mode(value:VoicePhase){this.phase=value;this.hooks.phase(value)}
 speaking(){if(!this.active)return;this.abortRecognition();this.loudAt=0;this.speakingAt=performance.now();this.mode('speaking')}
 thinking(){this.abortRecognition();this.mode('thinking')}
 listen(){if(!this.active||this.recognition)return;this.mode('listening');const R=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition,r=new R();this.recognition=r;const epoch=this.epoch;let text='',failed=false,delivered=false;const confidences:number[]=[];r.lang='en-GB';r.continuous=true;r.interimResults=true;
 r.onresult=(event:any)=>{if(!this.active||this.recognition!==r)return;const parts:string[]=[];confidences.length=0;for(let i=0;i<event.results.length;i++){parts.push(event.results[i][0].transcript||'');if(event.results[i][0].confidence>0)confidences.push(event.results[i][0].confidence)}text=parts.join(' ').trim();if(this.timer)clearTimeout(this.timer);if(text)this.timer=setTimeout(()=>r.stop(),1300)};
 r.onerror=(event:any)=>{if(this.recognition!==r)return;if(['not-allowed','service-not-allowed','audio-capture','network'].includes(event.error)){failed=true;this.hooks.error(event.error==='network'?'Ovozni tanish xizmati bilan aloqa yo‘q. Internetni tekshirib qayta boshlang.':'Brauzer sayt ruxsatlarida mikrofonga ruxsat bering.');this.stop()}else if(event.error==='aborted')failed=true};
 r.onend=()=>{if(this.recognition!==r)return;this.recognition=null;if(this.timer)clearTimeout(this.timer);if(!this.active||epoch!==this.epoch||failed||delivered)return;delivered=true;if(text&&(!confidences.length||confidences.reduce((a,b)=>a+b,0)/confidences.length>=.5)){this.mode('thinking');this.hooks.utterance(text)}else{if(text)this.hooks.error('Ovoz aniq tushunilmadi. Yana ayting.');this.retry=setTimeout(()=>this.listen(),400)}};
 try{r.start()}catch{this.recognition=null;this.hooks.error('Mikrofonni qayta boshlang.');this.stop()}}
 private abortRecognition(){if(this.timer)clearTimeout(this.timer);if(this.retry)clearTimeout(this.retry);const r=this.recognition;this.recognition=null;r?.abort()}
 private monitor(){if(!this.active||!this.analyser)return;const values=new Float32Array(this.analyser.fftSize);this.analyser.getFloatTimeDomainData(values);const rms=Math.sqrt(values.reduce((sum,v)=>sum+v*v,0)/values.length),now=performance.now();if(this.phase==='listening'&&rms<.03)this.baseline=.96*this.baseline+.04*rms;
 if(this.phase==='speaking'&&now-this.speakingAt>500){if(rms>Math.max(.045,this.baseline*5)){if(!this.loudAt)this.loudAt=now;if(now-this.loudAt>180){this.hooks.interrupt();this.listen();this.loudAt=0}}else this.loudAt=0}this.frame=requestAnimationFrame(()=>this.monitor())}
 stop(){this.active=false;this.epoch++;cancelAnimationFrame(this.frame);this.abortRecognition();this.stream?.getTracks().forEach(t=>t.stop());this.stream=null;void this.context?.close().catch(()=>{});this.context=null;this.analyser=null;this.mode('idle')}
}
