const fs=require('fs'),vm=require('vm'),ts=require('typescript'),path=require('path'),assert=require('assert');const root=process.cwd();
function setup(handler){const cache={};function load(file){file=path.resolve(file);if(cache[file])return cache[file].exports;const m={exports:{}};cache[file]=m;const req=id=>id.startsWith('.')?load(path.resolve(path.dirname(file),id)+'.ts'):require(id);vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{module:m,exports:m.exports,require:req,process:{env:{}},Buffer,Response,AbortSignal,fetch:handler,Map,Set,Date,setTimeout,clearTimeout,console},{filename:file});return m.exports}return load(root+'/lib/tts.ts').generateVoice}
const pcm=Buffer.alloc(48,1),args={apiKey:'fake-key',text:'The little boy walked slowly to school.',voice:'Kore'};
(async()=>{
let calls=0,body;let generate=setup(async(url,o)=>{calls++;body=JSON.parse(o.body);assert(url.includes('gemini-3.8-flash-lite-tts:generateContent'));return Response.json({candidates:[{content:{parts:[{inlineData:{mimeType:'audio/L16;rate=24000',data:pcm.toString('base64')}}]}}]})});
const [a,b]=await Promise.all([generate(args),generate(args)]);assert.equal(calls,1);assert.equal(a,b);assert.equal(body.contents[0].parts[0].text,args.text);assert(body.contents[0].parts[0].speech_metadata.style);assert.equal(body.generationConfig.speechConfig.voiceConfig.voice,'Kore');assert.equal(a.bytes.toString('ascii',0,4),'RIFF');assert.equal(a.bytes.length,pcm.length+44);await generate(args);assert.equal(calls,1);
await generate({...args,purpose:'book'});assert.equal(calls,2);assert(body.contents[0].parts[0].speech_metadata.style.includes('audiobook narrator'));assert(body.contents[0].parts[0].speech_metadata.style.includes('word for word'));assert.equal(body.contents[0].parts[0].text,args.text);await generate({...args,purpose:'book'});assert.equal(calls,2);
const wav=a.bytes;generate=setup(async()=>Response.json({candidates:[{content:{parts:[{inlineData:{mimeType:'audio/wav',data:wav.toString('base64')}}]}}]}));assert.deepEqual((await generate(args)).bytes,wav);
const models=[];generate=setup(async(url,o)=>{models.push(url);if(models.length===1)return Response.json({error:{message:'model not found'}},{status:404});body=JSON.parse(o.body);return Response.json({candidates:[{content:{parts:[{inlineData:{mimeType:'audio/L16;rate=24000',data:pcm.toString('base64')}}]}}]})});assert.equal((await generate(args)).model,'gemini-2.5-flash-preview-tts');assert.equal(models.length,2);assert.equal(body.generationConfig.speechConfig.voiceConfig.prebuiltVoiceConfig.voiceName,'Kore');await generate({...args,text:'Another line.'});assert(models[2].includes('2.5-flash-preview-tts'));
calls=0;generate=setup(async()=>{calls++;return Response.json({error:{message:'quota exceeded'}},{status:429})});await assert.rejects(()=>generate(args),e=>e.code==='AI_QUOTA');assert.equal(calls,1);
generate=setup(async()=>{throw new Error('aborted')});await assert.rejects(()=>generate(args),e=>e.code==='VOICE_TIMEOUT');
generate=setup(async()=>Response.json({candidates:[{content:{parts:[]}}]}));await assert.rejects(()=>generate(args),e=>e.code==='VOICE_EMPTY');
generate=setup(async(url,o)=>{assert(url.endsWith('/interactions'));body=JSON.parse(o.body);assert.equal(body.generation_config.speech_config[0].voice,'voice_private');assert.equal(body.input[0].content[0].text,args.text);return Response.json({steps:[{type:'model_output',content:[{type:'audio',data:wav.toString('base64'),mime_type:'audio/wav'}]}]})});assert.deepEqual((await generate({...args,voice:'voice_private',personal:true,model:'gemini-3.8-flash-tts'})).bytes,wav);
console.log('PASS: modern verbatim TTS, legacy fallback, personal voice, PCM/WAV decoding, in-flight dedupe and cache; quota/empty/timeout are explicit errors.');
})().catch(e=>{console.error(e);process.exit(1)});
