const fs=require('fs'),ts=require('typescript'),vm=require('vm'),path=require('path'),crypto=require('crypto'),assert=require('assert');const root=process.cwd(),cache={},tables={},calls=[],readCalls=[];const day=new Date(Date.now()+5*3600000).toISOString().slice(0,10),settings={language:'en',style:'classic',layout:'cards',accent:'',audioRate:.7};
const roles=[['owner','o','platform'],['advertiser','a','platform'],['student','s','zamon'],['teacher','t','zamon'],['admin','h','zamon'],['administrator','m','zamon'],['student','other','other']];tables.school_users=roles.map(([role,id,center_id])=>({id,role,identity:id,login_name:id,first_name:id,last_name:'Test',center_id,group_id:role==='student'||role==='admin'?'g':null,book:'a1',unlocked_unit:1,start_unit:1,start_lesson:1,settings:{...settings},billing:{status:'paid',paidAt:day}}));tables.school_sessions=roles.map(([role,id])=>({id:crypto.createHash('sha256').update(id).digest('hex'),token:crypto.createHash('sha256').update(id).digest('hex'),user_id:id,expires_at:new Date(Date.now()+86400000).toISOString()}));tables.school_groups=[{id:'g',teacher_id:'t',center_id:'zamon',days:[2],time:'16:00',reminder_time:'09:00'}, {id:'other-group',teacher_id:'t-other',center_id:'other',days:[2],time:'16:00',reminder_time:'09:00'},{id:'g2',teacher_id:'t2',center_id:'zamon',days:[2],time:'16:00',reminder_time:'09:00'}];tables.school_centers=[{id:'other',name:'Other'}];tables.school_attempts=[{id:'attempt-s',user_id:'s',center_id:'zamon'}, {id:'attempt-other',user_id:'other',center_id:'other'}];
function matches(r,q){return [...new URLSearchParams(q)].every(([k,v])=>{if(['order','limit','on_conflict'].includes(k))return true;const [op,...a]=v.split('.'),value=a.join('.');return op==='eq'?String(r[k])===value:op==='gt'?String(r[k])>value:true})}
async function firebaseDb(table,method='GET',data,q=''){if(table==='rpc/school_login_guard')return true;const rows=tables[table]||(tables[table]=[]),found=rows.filter(r=>matches(r,q));if(method==='GET'){readCalls.push(table+'|'+q);return structuredClone(found);}calls.push({table,method,data:structuredClone(data)});if(method==='POST'){const id=data.id||crypto.createHash('sha256').update(data.identity||crypto.randomUUID()).digest('hex');if(rows.some(r=>r.id===id)){const e=new Error('Exists');e.status=409;throw e}const row={...data,id};if(table==='school_users'){row.settings??={...settings};row.billing??={status:'paid',paidAt:day};row.center_id??='zamon'}rows.push(row);return structuredClone([row])}if(method==='PATCH'){found.forEach(r=>Object.assign(r,data));return structuredClone(found)}if(method==='DELETE'){tables[table]=rows.filter(r=>!found.includes(r));return[]}throw Error('unsupported')}
const adapter={db:firebaseDb,createOwnerSession:async()=>true,moveSchoolUserCenter:async()=>true,activateTeacher:async()=>true,claimPendingTeacher:async()=>true,createAdministrator:async()=>true,resignTemporaryAdministrator:async()=>true};
function load(file){file=path.resolve(file);if(cache[file])return cache[file].exports;const m={exports:{}};cache[file]=m;const req=id=>id==='server-only'?{}:id==='web-push'?{setVapidDetails(){},sendNotification(){}}:id.endsWith('firebase-store.mjs')?adapter:id.startsWith('@/')?load(root+'/'+id.slice(2)+(path.extname(id)?'':'.ts')):id.startsWith('.')?load(path.resolve(path.dirname(file),id)+(path.extname(id)?'':'.ts')):require(id);if(file.endsWith('.json')){m.exports=JSON.parse(fs.readFileSync(file));return m.exports}vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText,{require:req,module:m,exports:m.exports,console,Buffer,process,Map,Set,Date,URLSearchParams,structuredClone,Error,setTimeout,clearTimeout,Response,Request,Headers,URL,AbortSignal,fetch},{filename:file});return m.exports}
function request(id,mode={},data){return new Request('http://localhost/api/test',{method:data?'POST':'GET',headers:{cookie:'school_session='+id,host:'localhost',...mode},...(data?{body:JSON.stringify(data)}:{})})}
(async()=>{const server=load(root+'/lib/school-server.ts'),context=load(root+'/lib/center-context.ts');
await context.schoolScope(async()=>{await server.current(request('o'));const n=readCalls.length;const [a,b]=await Promise.all([server.db('school_users','GET',null,'id=eq.s'),server.db('school_users','GET',null,'id=eq.s')]);assert.equal(readCalls.length-n,1);a[0].first_name='Private copy';assert.notEqual(b[0].first_name,'Private copy');await server.db('school_users','PATCH',{cache_test:1},'id=eq.s');assert.equal((await server.db('school_users','GET',null,'id=eq.s'))[0].cache_test,1)});const count=readCalls.length;await context.schoolScope(async()=>{await server.current(request('o'));await server.db('school_users','GET',null,'id=eq.s')});assert(readCalls.length>count);
for(const role of ['s','a','t','h'])await context.schoolScope(async()=>{await assert.rejects(()=>server.current(request(role,{'X-Owner-User':'s'})),e=>e.status===403)});
await context.schoolScope(async()=>{await assert.rejects(()=>server.current(request('s',{'X-Demo-Role':'teacher','X-Demo-Key':'abcdefghijklmnop'})),e=>e.status===403)});
await context.schoolScope(async()=>{const u=await server.current(request('o',{'X-Owner-User':'s','X-Center-ID':'other'}));assert.equal(u.id,'s');assert.equal(context.centerContext.getStore().centerId,'zamon');await server.db('school_users','PATCH',{unlocked_unit:2},'id=eq.s');assert.equal(tables.school_users.find(u=>u.id==='s').unlocked_unit,2)});
const before=JSON.stringify(tables),writeCount=calls.length;
await context.schoolScope(async()=>{const u=await server.current(request('a',{'X-Demo-Role':'teacher','X-Demo-Key':'abcdefghijklmnop'}));assert.equal(u.id,'demo-teacher');await server.db('school_users','PATCH',{first_name:'Changed'},'id=eq.demo-student');assert.equal((await server.db('school_users','GET',null,'id=eq.demo-student'))[0].first_name,'Changed')});assert.equal(JSON.stringify(tables),before);assert.equal(calls.length,writeCount);
await context.schoolScope(async()=>{await server.current(request('h'));const users=await server.db('school_users');assert(users.every(u=>u.id==='h'||u.group_id==='g'));await assert.rejects(()=>server.db('school_attempts','PATCH',{grade:100},'id=eq.attempt-other'),e=>e.status===403);assert((await server.db('school_groups')).every(g=>g.id==='g'));assert.throws(()=>server.administrator({role:'admin'}));assert.throws(()=>server.teacher({role:'admin'}))});
const school=load(root+'/app/api/school/route.ts'),platform=load(root+'/app/api/platform/route.ts');const ownerSnapshot=JSON.stringify(tables),ownerWrites=calls.length;const homeMode={'X-Demo-Role':'advertiser','X-Demo-Key':'abcdefghijklmnop'};let home=await school.POST(request('o',homeMode,{action:'settings',settings:{...settings,language:'uz',voice:'Puck'}}));assert.equal(home.status,200);assert.equal(JSON.stringify(tables),ownerSnapshot);assert.equal(calls.length,ownerWrites);let response=await school.GET(request('a'));assert.equal(response.status,200);let d=await response.json();assert.equal(d.users.length,0);assert.equal(d.groups.length,0);assert.equal(d.voiceOptions.length,5);
response=await platform.POST(request('s',{}, {action:'centerPayment',centerId:'zamon',status:'unpaid'}));assert.equal(response.status,403);
response=await platform.POST(request('o',{}, {action:'centerPayment',centerId:'zamon',status:'unpaid'}));assert.equal(response.status,200);assert.equal(tables.school_centers.find(c=>c.id==='zamon').billing.status,'unpaid');assert(tables.school_inbox.some(n=>n.user_id==='m'&&n.kind==='center-payment'));
response=await platform.POST(request('s',{}, {action:'suggestion',body:'Yaxshi taklif'}));assert.equal(response.status,200);assert(tables.school_inbox.some(n=>n.user_id==='o'&&n.kind==='suggestion'));assert(tables.school_inbox.some(n=>n.user_id==='a'&&n.kind==='suggestion'));
response=await platform.GET(request('a'));d=await response.json();assert.equal(d.users.length,0);assert.equal(d.centers.length,0);
const broadcast={action:'centerEvent',all:false,centers:['other'],title:'Special class',at:new Date(Date.now()+86400000).toISOString(),broadcastId:crypto.randomUUID()};response=await platform.POST(request('o',{},broadcast));if(response.status!==200)console.log(await response.clone().json());assert.equal(response.status,200);assert.equal(tables.school_events.length,1);assert.equal(tables.school_events[0].center_id,'other');response=await platform.POST(request('o',{},broadcast));if(response.status!==200)console.log(await response.clone().json());assert.equal(response.status,200);assert.equal(tables.school_events.length,1);assert(tables.school_inbox.some(n=>n.user_id==='other'&&n.kind==='event'));
const auth=load(root+'/app/api/auth/route.ts');process.env.ADVERTISER_ACCESS_CODE='demo12345678';process.env.OWNER_ACCESS_CODE='owner12345678';process.env.TEACHER_ACCESS_CODE='teach12345678';process.env.ADMINISTRATOR_ACCESS_CODE='admin12345678';response=await auth.POST(request('s',{}, {action:'verifyTeacherCode',role:'teacher',code:'demo12345678'}));assert.equal(response.status,200);const ticket=response.headers.get('set-cookie').split(';')[0];response=await auth.POST(new Request('http://localhost/api/auth',{method:'POST',headers:{cookie:ticket,host:'localhost'},body:JSON.stringify({action:'registerAdvertiser',role:'advertiser',firstName:'Same',lastName:'Name',password:'password123'})}));assert.equal(response.status,200);d=await response.json();assert.equal(d.user.role,'advertiser');const ar=tables.school_users.find(u=>u.identity==='advertiser|same name');assert(ar);assert.equal(ar.center_id,'platform');tables.school_users.push({...ar,id:'realstudent',identity:'same name',role:'student',center_id:'zamon'});response=await auth.POST(request('s',{}, {action:'login',role:'teacher',firstName:'Same',lastName:'Name',password:'password123'}));assert.equal(response.status,200);d=await response.json();assert.equal(d.user.id,ar.id);assert.notEqual(d.user.id,'realstudent');
response=await school.POST(request('t',{}, {action:'group',id:'g',name:'Test lessons',days:[2,4,6],time:'16:00',reminderTime:'09:00'}));assert.equal(response.status,200);response=await school.POST(request('t',{}, {action:'assignment',title:'Group homework',text:'Read Unit 2',groups:['g'],extra:false}));assert.equal(response.status,200);response=await school.GET(request('s'));assert.equal(response.status,200);d=await response.json();assert.deepEqual(d.groups.find(g=>g.id==='g').days,[2,4,6]);assert.equal(d.groups.find(g=>g.id==='g').time,'16:00');assert(d.assignments.some(a=>a.title==='Group homework'));response=await school.GET(request('other'));d=await response.json();assert(!d.assignments.some(a=>a.title==='Group homework'));
const msgid='22222222-2222-4222-8222-222222222222';response=await platform.POST(request('o',{}, {action:'centerMessage',centers:['zamon'],title:'Owner message',body:'Please read',broadcastId:msgid}));assert.equal(response.status,200);const messages=tables.school_inbox.filter(n=>n.kind==='message'&&n.ref===msgid);assert.equal(messages.length,1);assert.equal(messages[0].user_id,'m');response=await school.POST(request('s',{}, {action:'notificationsRead',ids:[messages[0].id]}));assert.equal(response.status,403);response=await school.POST(request('m',{}, {action:'notificationsRead',ids:[messages[0].id]}));assert.equal(response.status,200);assert(tables.school_inbox.find(n=>n.id===messages[0].id).read);response=await platform.POST(request('o',{}, {action:'centerMessage',centers:['zamon'],title:'Owner message',body:'Please read',broadcastId:msgid}));assert.equal(response.status,200);assert.equal(tables.school_inbox.filter(n=>n.kind==='message'&&n.ref===msgid).length,1);
const audio=JSON.parse(fs.readFileSync(root+'/lib/data/audio-catalog.json'));const future=audio.find(t=>t.book==='a2'&&t.unit===5)||audio.at(-1);const media=load(root+'/app/api/media/route.ts');response=await media.GET(new Request('http://localhost/api/media?path='+encodeURIComponent(future.path),{headers:{cookie:'school_session=s'}}));assert.equal(response.status,200);
process.env.GEMINI_API_KEY='test-key-not-real-123456789';process.env.ODINA_VOICE_USER_ID='s';process.env.ODINA_VOICE_ID='voice_abc';const voices=load(root+'/lib/voice-server.ts');assert.equal(voices.userVoices({id:'s'}).length,6);assert.equal(voices.userVoices({id:'other',firstName:'s'}).length,5);let voiceCall;global.fetch=async(url,options)=>{voiceCall={url,body:JSON.parse(options.body)};return Response.json({steps:[{type:'model_output',content:[{type:'audio',data:Buffer.from('sample').toString('base64'),mime_type:'audio/wav'}]}]})};const voice=load(root+'/app/api/voice/route.ts');response=await voice.POST(request('s',{}, {text:'Hello.',voice:'personal'}));assert.equal(response.status,200);assert(voiceCall.url.endsWith('/interactions'));assert.equal(voiceCall.body.generation_config.speech_config[0].voice,'voice_abc');response=await voice.POST(request('other',{}, {text:'Hello.',voice:'personal'}));assert.equal(response.status,403);
tables.school_users.find(u=>u.id==='t').identity='t test';tables.school_users.find(u=>u.id==='t').login_name='t test';
for(const id of ['t','h','m','s'])tables.school_users.find(u=>u.id===id).password_hash=server.hashPassword('oldpassword123');
let snapshot=JSON.stringify(tables);response=await school.POST(request('t',{}, {action:'profile',firstName:'Teacher',lastName:'Renamed',currentPassword:'wrongpassword',personalCode:'teacherSelf1'}));assert.equal(response.status,403);assert.equal(JSON.stringify(tables),snapshot);
for(const [id,code] of [['t','teacherSelf1'],['h','helperSelf12'],['m','managerSelf1']]){response=await school.POST(request(id,{}, {action:'profile',firstName:id==='t'?'Teacher':id,lastName:'Renamed',currentPassword:'oldpassword123',personalCode:code}));assert.equal(response.status,200);response=await auth.POST(request('s',{}, {action:'verifyTeacherCode',role:'teacher',code,centerId:'wrong-center'}));assert.equal(response.status,200);d=await response.json();assert(d.loggedIn);assert.equal(d.user.id,id);assert(!JSON.stringify(d).includes('teacher_code_hash'));}
response=await school.POST(request('s',{}, {action:'profile',firstName:'Student',lastName:'Renamed',currentPassword:'oldpassword123',personalCode:'studentSelf1'}));assert.equal(response.status,403);
response=await school.POST(request('t',{}, {action:'profile',firstName:'Teacher',lastName:'Renamed',currentPassword:'oldpassword123',newPassword:'newpassword123',personalCode:'teacherSelf2'}));assert.equal(response.status,200);response=await auth.POST(request('s',{}, {action:'verifyTeacherCode',role:'teacher',code:'teacherSelf1'}));assert.equal(response.status,403);response=await auth.POST(request('s',{}, {action:'verifyTeacherCode',role:'teacher',code:'teacherSelf2'}));assert.equal(response.status,200);response=await auth.POST(request('s',{}, {action:'login',role:'teacher',firstName:'Teacher',lastName:'Renamed',password:'newpassword123'}));assert.equal(response.status,200);response=await auth.POST(request('s',{}, {action:'login',role:'teacher',firstName:'t',lastName:'Test',password:'newpassword123'}));assert.notEqual(response.status,200);
response=await school.POST(request('h',{}, {action:'profile',firstName:'h',lastName:'Renamed',currentPassword:'oldpassword123',personalCode:'teacherSelf2'}));assert.equal(response.status,409);tables.school_users.find(u=>u.id==='t').disabled=true;response=await auth.POST(request('s',{}, {action:'verifyTeacherCode',role:'teacher',code:'teacherSelf2'}));assert.equal(response.status,403);tables.school_users.find(u=>u.id==='t').disabled=false;
response=await auth.POST(request('s',{}, {action:'verifyTeacherCode',role:'teacher',code:'teach12345678',centerId:'zamon'}));assert.equal(response.status,200);const teacherTicket=response.headers.get('set-cookie').split(';')[0];response=await auth.POST(new Request('http://localhost/api/auth',{method:'POST',headers:{cookie:teacherTicket,host:'localhost'},body:JSON.stringify({action:'registerTeacher',role:'teacher',centerId:'zamon',firstName:'New',lastName:'Teacher',password:'newpassword123',personalCode:'NewTeacher12'})}));assert.equal(response.status,200);const newTeacher=(await response.json()).user;response=await auth.POST(request('s',{}, {action:'verifyTeacherCode',role:'teacher',code:'NewTeacher12'}));assert.equal(response.status,200);assert.equal((await response.json()).user.id,newTeacher.id);
const beforeDuplicate=tables.school_users.length;response=await auth.POST(new Request('http://localhost/api/auth',{method:'POST',headers:{cookie:teacherTicket,host:'localhost'},body:JSON.stringify({action:'registerTeacher',role:'teacher',centerId:'zamon',firstName:'Other',lastName:'Teacher',password:'newpassword123',personalCode:'NewTeacher12'})}));assert.equal(response.status,409);assert.equal(tables.school_users.length,beforeDuplicate);
const originalOwnerSession=adapter.createOwnerSession;
adapter.createOwnerSession=async()=>{throw Object.assign(new Error('Limit'),{code:'OWNER_DEVICE_LIMIT'})};
response=await auth.POST(request('s',{}, {action:'verifyTeacherCode',role:'teacher',code:process.env.OWNER_ACCESS_CODE}));assert.equal(response.status,409);assert((await response.json()).error.includes('3 ta qurilma limiti to‘lgan'));assert(!response.headers.get('set-cookie'));
adapter.createOwnerSession=async()=>{throw Object.assign(new Error('Database unavailable'),{status:503})};
response=await auth.POST(request('s',{}, {action:'verifyTeacherCode',role:'teacher',code:process.env.OWNER_ACCESS_CODE}));assert.equal(response.status,503);d=await response.json();assert(d.error.includes('server xatosi'));assert(!d.error.includes('limiti to‘lgan'));
adapter.createOwnerSession=originalOwnerSession;
console.log('PASS: Owner device limit returns readable 409 JSON, other session failures return distinct 503 JSON');
const platformOwner=tables.school_users.find(r=>r.identity==='__platform_owner__');assert(platformOwner);
const ownerToken='owner-profile';tables.school_sessions.push({id:server.digest(ownerToken),token:server.digest(ownerToken),user_id:platformOwner.id,expires_at:new Date(Date.now()+86400000).toISOString()});
let unchanged=JSON.stringify(tables);response=await school.POST(request(ownerToken,{}, {action:'profile',firstName:'Abduyx15870',lastName:'',currentCode:'wrong-owner',personalCode:'OwnerNew1234'}));assert.equal(response.status,403);assert.equal(JSON.stringify(tables),unchanged);
response=await school.POST(request(ownerToken,{}, {action:'profile',firstName:'Abduyx15870',lastName:'',currentCode:process.env.OWNER_ACCESS_CODE,personalCode:'OwnerNew1234'}));assert.equal(response.status,200);
response=await auth.POST(request('s',{}, {action:'verifyTeacherCode',role:'teacher',code:process.env.OWNER_ACCESS_CODE}));assert.equal(response.status,403);
response=await auth.POST(request('s',{}, {action:'verifyTeacherCode',role:'teacher',code:'OwnerNew1234',centerId:'wrong-center'}));assert.equal(response.status,200);d=await response.json();assert.equal(d.user.role,'owner');assert.equal(d.user.firstName,'Abduyx15870');assert(!JSON.stringify(d).includes('teacher_code_hash'));
response=await school.POST(request(ownerToken,{}, {action:'profile',firstName:'Abduyx15870',lastName:'',currentCode:'OwnerNew1234',personalCode:'OwnerNew5678'}));assert.equal(response.status,200);response=await auth.POST(request('s',{}, {action:'verifyTeacherCode',role:'teacher',code:'OwnerNew1234'}));assert.equal(response.status,403);
tables.school_users.find(r=>r.id==='a').password_hash=server.hashPassword('advertiserpass123');
response=await school.POST(request('a',{}, {action:'profile',firstName:'Reklamachi',lastName:'Test',currentPassword:'advertiserpass123',personalCode:'AdvertNew123'}));assert.equal(response.status,200);response=await auth.POST(request('s',{}, {action:'verifyTeacherCode',role:'teacher',code:'AdvertNew123',centerId:'wrong-center'}));assert.equal(response.status,200);assert.equal((await response.json()).user.id,'a');
response=await school.POST(request('a',{}, {action:'profile',firstName:'Reklamachi',lastName:'Test',currentPassword:'advertiserpass123',personalCode:'AdvertNew456'}));assert.equal(response.status,200);response=await auth.POST(request('s',{}, {action:'verifyTeacherCode',role:'teacher',code:'AdvertNew123'}));assert.equal(response.status,403);
console.log('PASS: Owner current-code verification, database code overrides old environment code, code rotation; advertiser personal code login without centre');
console.log('PASS: staff personal codes direct login, current password enforced, student code denied, code collision/rotation/disabled staff, renamed password login, new teacher chooses code');
console.log('PASS: Owner account switching saves, forged modes denied, demo zero real writes, Admin group boundary, center billing, targeted/idempotent events, suggestions, same-name advertiser auth, future media available, private sixth voice ID enforcement');
})().catch(e=>{console.error(e);process.exit(1)});
