const fs=require('fs'),ts=require('typescript'),vm=require('vm'),path=require('path'),crypto=require('crypto'),assert=require('assert');const root=process.cwd(),cache={},tables={},calls=[],readCalls=[];const day=new Date(Date.now()+5*3600000).toISOString().slice(0,10),settings={language:'en',style:'classic',layout:'cards',accent:'',audioRate:.7};
const roles=[['owner','o','platform'],['advertiser','a','platform'],['student','s','zamon'],['teacher','t','zamon'],['admin','h','zamon'],['administrator','m','zamon'],['student','other','other']];tables.school_users=roles.map(([role,id,center_id])=>({id,role,identity:id,login_name:id,first_name:id,last_name:'Test',center_id,group_id:role==='student'||role==='admin'?'g':null,book:'a1',unlocked_unit:1,start_unit:1,start_lesson:1,settings:{...settings},billing:{status:'paid',paidAt:day}}));tables.school_sessions=roles.map(([role,id])=>({id:crypto.createHash('sha256').update(id).digest('hex'),token:crypto.createHash('sha256').update(id).digest('hex'),user_id:id,expires_at:new Date(Date.now()+86400000).toISOString()}));tables.school_groups=[{id:'g',teacher_id:'t',center_id:'zamon',days:[2],time:'16:00',reminder_time:'09:00'}, {id:'other-group',teacher_id:'t-other',center_id:'other',days:[2],time:'16:00',reminder_time:'09:00'},{id:'g2',teacher_id:'t2',center_id:'zamon',days:[2],time:'16:00',reminder_time:'09:00'}];tables.school_centers=[{id:'other',name:'Other'}];tables.school_attempts=[{id:'attempt-s',user_id:'s',center_id:'zamon'}, {id:'attempt-other',user_id:'other',center_id:'other'}];
function matches(r,q){return [...new URLSearchParams(q)].every(([k,v])=>{if(['order','limit','on_conflict'].includes(k))return true;const [op,...a]=v.split('.'),value=a.join('.');return op==='eq'?String(r[k])===value:op==='gt'?String(r[k])>value:true})}
async function firebaseDb(table,method='GET',data,q=''){if(table==='rpc/school_login_guard')return true;const rows=tables[table]||(tables[table]=[]),found=rows.filter(r=>matches(r,q));if(method==='GET'){readCalls.push(table+'|'+q);return structuredClone(found);}calls.push({table,method,data:structuredClone(data)});if(method==='POST'){const id=data.id||crypto.createHash('sha256').update(data.identity||crypto.randomUUID()).digest('hex');if(rows.some(r=>r.id===id)){const e=new Error('Exists');e.status=409;throw e}const row={...data,id};if(table==='school_users'){row.settings??={...settings};row.billing??={status:'paid',paidAt:day};row.center_id??='zamon'}rows.push(row);return structuredClone([row])}if(method==='PATCH'){found.forEach(r=>Object.assign(r,data));return structuredClone(found)}if(method==='DELETE'){tables[table]=rows.filter(r=>!found.includes(r));return[]}throw Error('unsupported')}
const voiceInputs=[];const adapter={claimExamWindow:async data=>{const rows=tables.school_exam_windows||=[];const old=rows.find(x=>x.user_id===data.user_id&&x.exam===data.exam);if(old?.session_id===data.session_id)return old.suite_id===data.suite_id&&old.center_id===data.center_id?old:{conflict:true};if(old&&Date.parse(old.next_at)>Date.now())return {blocked:true,next_at:old.next_at};const v={...data,id:crypto.randomUUID(),next_at:new Date(Date.now()+14*86400000).toISOString()};if(old)Object.assign(old,v);else rows.push(v);return v},db:firebaseDb,createOwnerSession:async()=>true,moveSchoolUserCenter:async()=>true,activateTeacher:async()=>true,claimPendingTeacher:async()=>true,createAdministrator:async()=>true,resignTemporaryAdministrator:async()=>true};
function load(file){file=path.resolve(file);if(cache[file])return cache[file].exports;const m={exports:{}};cache[file]=m;const req=id=>id==='@/lib/tts'?{generateVoice:async body=>{voiceInputs.push({...body,language:body.language==='English'?'en':'uz'});return{bytes:Buffer.alloc(144),mime:'audio/wav'}}}:id==='server-only'?{}:id==='web-push'?{setVapidDetails(){},sendNotification(){}}:id.endsWith('firebase-store.mjs')?adapter:id.startsWith('@/')?load(root+'/'+id.slice(2)+(path.extname(id)?'':'.ts')):id.startsWith('.')?load(path.resolve(path.dirname(file),id)+(path.extname(id)?'':'.ts')):require(id);if(file.endsWith('.json')){m.exports=JSON.parse(fs.readFileSync(file));return m.exports}vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText,{require:req,module:m,exports:m.exports,console,Buffer,process,Map,Set,Date,URLSearchParams,structuredClone,Error,setTimeout,clearTimeout,Response,Request,Headers,URL,AbortSignal,fetch:(...args)=>global.fetch(...args)},{filename:file});return m.exports}
function request(id,mode={},data){return new Request('http://localhost/api/test',{method:data?'POST':'GET',headers:{cookie:'school_session='+id,host:'localhost',...mode},...(data?{body:JSON.stringify(data)}:{})})}

(async()=>{
 const api=load(root+'/app/api/exams/route.ts'),bank=load(root+'/lib/exams.ts');
 const get=(id,extra='',center='zamon')=>new Request('http://localhost/api/exams?center='+center+'&subject=english'+extra,{headers:{cookie:'school_session='+id}});
 const post=(id,data,center='zamon')=>new Request('http://localhost/api/exams?center='+center+'&subject=english',{method:'POST',headers:{cookie:'school_session='+id,host:'localhost'},body:JSON.stringify(data)});
 let r=await api.GET(get('s')),d=await r.json();assert.equal(r.status,200);assert(d.catalog.length>=8);assert(!JSON.stringify(d.catalog).includes('\"accepted\":'));assert(!JSON.stringify(d.catalog).includes('\"explanation\":'));
 const p=bank.exams.find(p=>p.id==='ielts-reading-1');assert.equal(bank.gradeObjective(p,{'1':' true ','2':'FALSE','3':'not given','4':'TANKS','5':'40','6':'C','7':'B','8':'seeds'}).score,8);assert.equal(bank.gradeObjective(p,{'4':'water tanks'}).score,0);
 r=await api.POST(post('s',{action:'start',packId:p.id,key:'abcdefghijklmnop1'}));d=await r.json();assert.equal(r.status,200);const id=d.attempt.id;assert(Date.parse(d.attempt.deadline)>Date.now());assert.equal(d.attempt.user_id,'s');
 r=await api.POST(post('s',{action:'start',packId:p.id,key:'abcdefghijklmnop1'}));assert.equal((await r.json()).attempt.id,id);assert.equal(tables.school_exam_attempts.length,1);
 r=await api.GET(get('other','&id='+id,'other'));assert.equal(r.status,404);
 r=await api.POST(post('other',{action:'submit',id,answers:{}},'other'));assert.equal(r.status,403);
 r=await api.POST(post('s',{action:'save',id,answers:{'1':'TRUE'}}));assert.equal(r.status,200);
 r=await api.POST(post('s',{action:'submit',id,answers:{'1':'TRUE','2':'FALSE'},score:8,grade:9}));d=await r.json();assert.equal(d.attempt.score,2);assert.equal(d.attempt.grade,null);assert.equal(d.attempt.state,'completed');
 r=await api.POST(post('s',{action:'submit',id,answers:{'1':'FALSE'}}));assert.equal((await r.json()).attempt.score,2);
 r=await api.POST(post('s',{action:'save',id,answers:{}}));assert.equal(r.status,409);
 r=await api.POST(post('s',{action:'grade',id,grade:9,comment:'Fake'}));assert.equal(r.status,403);
 r=await api.GET(get('t','&id='+id));assert.equal(r.status,200);
 tables.school_exam_attempts.push({...tables.school_exam_attempts[0],id:'unassigned',user_id:'someone',group_id:'g2'});r=await api.GET(get('t','&id=unassigned'));assert.equal(r.status,404);
 r=await api.POST(post('s',{action:'start',packId:'cefr-writing-1',key:'abcdefghijklmnop2'}));const w=(await r.json()).attempt;
 r=await api.POST(post('s',{action:'submit',id:w.id,answers:{'1':'Dear friend, I hope you are well.','2':'Dear Manager, I am writing about the closure.','3':'Learning together gives us useful feedback.'}}));assert.equal(r.status,200);assert.equal((await r.json()).attempt.score,null);
 r=await api.POST(post('t',{action:'grade',id:w.id,grade:65,comment:'Clear ideas. Please develop your examples.'}));assert.equal(r.status,200);assert.equal((await r.json()).attempt.grade,65);assert(tables.school_inbox.some(n=>n.user_id==='s'));
 r=await api.POST(post('t',{action:'grade',id:w.id,grade:101,comment:'Invalid'}));assert.equal(r.status,400);
 r=await api.POST(post('s',{action:'start',packId:'ielts-speaking-1',key:'abcdefghijklmnop3'}));const sp=(await r.json()).attempt;
 r=await api.POST(post('s',{action:'submit',id:sp.id,answers:{}}));assert.equal(r.status,400);
 r=await api.POST(post('s',{action:'submit',id:sp.id,answers:{},recording:{mime:'text/html',data:'AA=='}}));assert.equal(r.status,400);
 r=await api.POST(post('s',{action:'submit',id:sp.id,answers:{},recording:{mime:'audio/webm',data:'AA=='}}));assert.equal(r.status,200);
 r=await api.GET(get('s'));assert(!JSON.stringify(await r.json()).includes('AA=='));
 for(const pack of bank.exams){const ids=bank.questions(pack).map(q=>q.id);assert.equal(new Set(ids).size,ids.length);if(['reading','listening'].includes(pack.skill)){assert(ids.length>0);for(const q of bank.questions(pack))assert(q.accepted.length)}}

 const expected={'ielts-full-reading-1':[40,3,60],'ielts-full-listening-1':[40,4,32],'cefr-full-reading-1':[35,5,60],'cefr-full-listening-1':[35,6,45]};
 for(const [id,[count,parts,minutes]] of Object.entries(expected)){const p=bank.exams.find(p=>p.id===id);assert.equal(bank.questions(p).length,count);assert.equal(p.groups.length,parts);assert.equal(p.minutes,minutes);assert.equal(bank.gradeObjective(p,Object.fromEntries(bank.questions(p).map(q=>[q.id,q.accepted[0]]))).score,count)}
 const chunks=load(root+'/lib/exams/audio.ts').examAudioChunks;for(const p of bank.exams.filter(p=>p.fullLength&&p.skill==='listening'))for(const g of p.groups){const c=chunks(g.script);assert(c.every(s=>s.length<=1000));assert.equal(c.join(' ').replace(/\s+/g,' ').trim(),g.script.replace(/\s+/g,' ').trim())}
 const scores=load(root+'/lib/exams/results.ts');assert.equal(scores.practiceBand(30,'listening'),7);assert.equal(scores.practiceBand(23,'reading'),6);assert.equal(scores.sectionPracticeScore({exam:'cefr',skill:'reading',score:35,total:35,grade:null}),75);assert.equal(scores.overallPracticeScore('ielts',[]),null);assert.equal(scores.overallPracticeScore('ielts',[{skill:'listening',exam:'ielts',state:'completed',score:30,total:40},{skill:'reading',exam:'ielts',state:'completed',score:30,total:40},{skill:'writing',exam:'ielts',state:'completed',score:null,grade:6},{skill:'speaking',exam:'ielts',state:'completed',score:null,grade:6}]),6.5);
 r=await api.POST(post('s',{action:'start',packId:'cefr-full-speaking-1',key:'fullspeakingtest12',sessionId:'fullsessiontest12'}));let full=(await r.json()).attempt;assert.equal(full.session_id,'fullsessiontest12');
 r=await api.POST(post('s',{action:'clip',id:full.id,stageId:'s2',recording:{mime:'audio/webm',data:'AA=='}}));assert.equal(r.status,409);
 for(let i=1;i<=8;i++){r=await api.POST(post('s',{action:'clip',id:full.id,stageId:'s'+i,recording:{mime:'audio/webm',data:'AA=='}}));assert.equal(r.status,200);assert.equal((await r.json()).clip.stage_id,'s'+i)}
 r=await api.POST(post('s',{action:'clip',id:full.id,stageId:'s1',recording:{mime:'audio/webm',data:'AB=='}}));assert.equal(r.status,200);assert.equal(tables.school_exam_clips.length,8);
 r=await api.GET(get('s','&id='+full.id));const cp=(await r.json()).attempt.clips;assert.equal(cp.length,8);assert(!JSON.stringify(cp).includes('AA=='));
 r=await api.GET(get('other','&id='+full.id+'&clip=s1','other'));assert.equal(r.status,404);
 r=await api.GET(get('t','&id='+full.id+'&clip=s1'));assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'audio/webm');
 r=await api.POST(post('s',{action:'submit',id:full.id,answers:{}}));assert.equal(r.status,200);assert.equal((await r.json()).attempt.clip_count,8);
 r=await api.POST(post('t',{action:'grade',id:full.id,grade:76,comment:'Too high'}));assert.equal(r.status,400);
 r=await api.POST(post('t',{action:'grade',id:full.id,grade:60,comment:'Clear speech and good organisation.'}));assert.equal(r.status,200);
 r=await api.POST(post('s',{action:'clip',id:full.id,stageId:'s1',recording:{mime:'audio/webm',data:'AA=='}}));assert.equal(r.status,409);

 // Server-enforced windows cannot be bypassed with a new device key or suite.
 r=await api.POST(post('s',{action:'start',packId:'cefr-full-reading-1',key:'anotherdevicekey12',sessionId:'anothersession12'}));assert.equal(r.status,429);
 r=await api.POST(post('s',{action:'start',packId:'cefr-full-reading-1',key:'nextskilldevice12',sessionId:'fullsessiontest12'}));assert.equal(r.status,200);const reading=(await r.json()).attempt;
 r=await api.POST(post('s',{action:'start',packId:'cefr-full-reading-1',key:'differentkeyagain12',sessionId:'fullsessiontest12'}));assert.equal((await r.json()).attempt.id,reading.id);
 r=await api.GET(get('s','&certificate=fullsessiontest12'));assert.equal(r.status,409);
 const suitePapers=bank.exams.filter(p=>p.fullLength&&p.exam==='ielts');
 r=await api.GET(get('s','&template=ielts'));assert.equal(r.status,403);
 r=await api.GET(get('t','&template=ielts'));assert.equal((await r.json()).packs.length,4);
 r=await api.POST(post('s',{action:'publish',title:'Student fake',packs:suitePapers}));assert.equal(r.status,403);
 r=await api.POST(post('t',{action:'publish',title:'Zamon custom mock',packs:suitePapers}));assert.equal(r.status,200);const suite=(await r.json()).suite;
 r=await api.GET(get('s'));d=await r.json();assert(d.catalog.some(p=>p.suiteId===suite.id));assert(!JSON.stringify(d.catalog).includes('"accepted":'));
 r=await api.GET(get('other','','other'));assert(!(await r.json()).catalog.some(p=>p.suiteId===suite.id));
 const broken=structuredClone(suitePapers);broken[0].groups[0].questions[0].accepted=[];
 r=await api.POST(post('t',{action:'publish',title:'Invalid keys',packs:broken}));assert.equal(r.status,400);
 r=await api.POST(post('s',{action:'start',packId:suite.id+'-reading',key:'customreaddevice12',sessionId:'customsessiontest12'}));assert.equal(r.status,200);const custom=(await r.json()).attempt;
 const original=bank.exams.find(p=>p.fullLength&&p.exam==='ielts'&&p.skill==='reading');r=await api.POST(post('s',{action:'submit',id:custom.id,answers:Object.fromEntries(bank.questions(original).map(q=>[q.id,q.accepted[0]]))}));assert.equal((await r.json()).attempt.score,40);
 r=await api.POST(post('s',{action:'start',packId:'ielts-full-listening-1',key:'suitebypasskey1234',sessionId:'customsessiontest12'}));assert.equal(r.status,409);
 r=await api.POST(post('t',{action:'archive',suiteId:suite.id}));assert.equal(r.status,200);
 r=await api.GET(get('s','&id='+custom.id));assert.equal((await r.json()).attempt.score,40);
 r=await api.POST(post('s',{action:'start',packId:suite.id+'-listening',key:'archivedkey123456',sessionId:'newarchivedsess12'}));assert.equal(r.status,409);
 fs.mkdirSync(root+'/tmp/pdfs',{recursive:true});fs.writeFileSync(root+'/tmp/pdfs/certificate-test.pdf',await load(root+'/lib/exams/certificate.ts').examCertificate({id:'LG-TEST',name:'Abdumalik O‘g‘li',center:'Zamon',title:'Mock 1',exam:'ielts',date:'2026-10-10',overall:7,scores:['listening','reading','writing','speaking'].map(skill=>({skill,score:7}))}));
 // Certificate needs all four, server-owned scores, and one candidate.
 const session='certificatecheck12';for(const skill of ['listening','reading','writing','speaking'])tables.school_exam_attempts.push({id:'cert-'+skill,center_id:'zamon',subject_id:'english',user_id:'s',pack_id:'cefr-full-'+skill+'-1',session_id:session,suite_id:'lingora-cefr',exam:'cefr',skill,state:'completed',created_at:new Date().toISOString(),completed_at:new Date().toISOString(),score:['listening','reading'].includes(skill)?35:null,total:35,grade:['writing','speaking'].includes(skill)?60:null,title:'Certificate test'});
 r=await api.GET(get('s','&certificate='+session));if(r.status!==200)console.log(await r.clone().text());assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'application/pdf');assert.equal(Buffer.from(await r.arrayBuffer()).subarray(0,4).toString(),'%PDF');
 r=await api.GET(get('other','&certificate='+session,'other'));assert.equal(r.status,404);
 tables.school_exam_attempts.find(x=>x.id==='cert-speaking').grade=null;r=await api.GET(get('s','&certificate='+session));assert.equal(r.status,409);
 tables.school_exam_windows.find(x=>x.exam==='cefr'&&x.user_id==='s').next_at=new Date(Date.now()-1).toISOString();
 r=await api.POST(post('s',{action:'start',packId:'cefr-full-listening-1',key:'after14dayskey123',sessionId:'after14session12'}));assert.equal(r.status,200);
 console.log('PASS: source-backed catalogue hides answer keys; case/word limits graded accurately; server owns score; start/submit idempotent; draft restored; student/teacher/centre permissions; recording bounds; manual grades and notifications.');
})().catch(e=>{console.error(e);process.exit(1)});
